"""S13 — renders `results/reconciliation/report.md` purely from the committed
tables (D13).

Scope, the species tree and the instrument live here; the results live in
`s13_report_results.py` (the `s3_report.py` / `s3_report_d10.py` split, so
both halves stay under 500 lines and take this module's loader and formatter
and so cannot read the tables differently).

Run:  python3 scripts/s13_report.py
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

OUT = Path(__file__).resolve().parents[1] / "results" / "reconciliation"


def load(name: str) -> list:
    p = OUT / name
    if not p.exists():
        return []
    with open(p) as fh:
        return list(csv.DictReader(fh, delimiter="\t"))


def load_json(name: str) -> dict:
    p = OUT / name
    return json.loads(p.read_text()) if p.exists() else {}


def num(v, nd=0) -> str:
    try:
        f = float(v)
    except (TypeError, ValueError):
        return str(v)
    return f"{f:,.{nd}f}"


def table(header: list, rows: list) -> list:
    out = ["| " + " | ".join(header) + " |",
           "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return out + [""]


def not_run(what: str) -> list:
    return [f"*{what} — **not run yet**.*\n"]


# ------------------------------------------------------------------ sections

def section_head(cal: list, summ: list) -> list:
    n_sp = len({r["node"] for r in cal})
    tips = max((int(r["n_tips"]) for r in cal), default=0)
    cells = [r for r in summ if not r.get("note")]
    L = [f"# S13 — where the duplications that made ITPR1/2/3 sit on the "
         f"vertebrate tree ({tips} species, {len(cells)} reconciliations)",
         "",
         "*Generated by `scripts/s13_report.py` from the committed tables in "
         "`results/reconciliation/`. Nothing here is hand-written (D13): every "
         "number is read from a file this task wrote, and the verdicts are "
         "computed by comparing those numbers against the priors the earlier "
         "tasks recorded.*", ""]
    L += ["## 1. What this task can and cannot answer", "",
          "Reconciliation gives a **placement**, not a date. S9 measured "
          "median pairwise dS *within* a single paralog set at 4.6-13.5, with "
          "84.6-94.2 % of within-paralog pairs past the dS = 1.5 saturation "
          "bar — so no molecular clock this project can run would date a "
          "duplication that is older still. What a gene tree and a species "
          "tree can do together is say which **branch** of the species tree an "
          "event falls on; the endpoints of that branch then bracket it, and "
          "the bracket is as narrow as the literature's ages for those two "
          "nodes and no narrower.", "",
          "Everything below is therefore stated as a placement with a bracket, "
          "and where the cells of the analysis disagree the disagreement is "
          "the result rather than something to average away.", ""]
    return L


def section_species_tree(cal: list) -> list:
    L = ["## 2. The species tree is an input, not a result (D15)", ""]
    if not cal:
        return L + not_run("the species tree")
    tips = max((int(r["n_tips"]) for r in cal), default=0)
    L += [f"A hand-curated topology for the **{tips} vertebrate species** the "
          f"S6 representative set samples, with **{len(cal)} named internal "
          f"nodes**, every one carrying a literature age, the spread of "
          f"published estimates and its source. It is validated before use: "
          f"`python3 scripts/s13_species_tree.py --check` fails on a gene-tree "
          f"species missing from the tree, on a species tree carrying a taxon "
          f"with no gene-tree tip, on an uncalibrated node, on a point age "
          f"outside its own spread, and on any age inversion.", ""]
    L += ["**Two design choices worth stating.** Where published estimates do "
          "not resolve an arrangement — the ovalentarian percomorphs here — "
          "the node is left a **polytomy** rather than given a shape the "
          "sources do not carry; the non-binary reconciliation handles it "
          "(§3). And every node carries a **`stem_age_ma`** beside its crown "
          "age: the sampled tree omits every lineage this project did not "
          "sequence, so a node's parent *in this tree* is usually older than "
          "the split that created it. With no marsupial sampled, "
          "Boreoeutheria's parent here is Amniota, and a duplication mapped to "
          "Boreoeutheria would be bracketed [96, 319] Ma when the honest "
          "bracket is [96, 99]. `--check` requires "
          "`age <= stem_age <= parent age`.", ""]
    deep = [r for r in cal if r["node"] in
            ("Vertebrata", "Cyclostomata", "Gnathostomata", "Chondrichthyes",
             "Osteichthyes", "Sarcopterygii", "Tetrapoda", "Amniota")]
    L += ["The nodes every conclusion below rests on, as committed in "
          "`species_tree_calibrations.tsv`:", ""]
    L += table(["node", "crown age (Ma)", "published spread", "stem age (Ma)",
                "species under it", "source"],
               [[f"**{r['node']}**", num(r["age_ma"], 0),
                 f"{num(r['age_lo'],0)}–{num(r['age_hi'],0)}",
                 num(r["stem_age_ma"], 0), r["n_tips"],
                 r["source"].split(";")[0]] for r in deep])
    L += ["The deep backbone is uncontroversial and fully sampled — no lineage "
          "sits between Vertebrata and Gnathostomata, or between Gnathostomata "
          "and its two daughters, that this tree omits — so for exactly the "
          "nodes the answer uses, the sampled parent *is* the true sister "
          "split and the stem age costs nothing.", "",
          "The shared deep calibrations are identical to the PIEZO project's "
          "curated table because both read the same published sources. That is "
          "a shared **input**, not a ported result.", ""]
    return L


def section_instrument(meta: dict, summ: list) -> list:
    L = ["## 3. The instrument", ""]
    par = meta.get("parameters", {})
    L += ["LCA reconciliation (Goodman et al. 1979; Page 1994), losses after "
          "Zmasek & Eddy 2001, implemented in the stdlib for the same reason "
          "S7 carries its own Newick code: the trees are small, the algorithm "
          "is exact and deterministic, and a hand-checkable implementation is "
          "worth more than a black box for a claim this load-bearing.", ""]
    L += ["**The duplication test is the non-binary one, and that is not a "
          "detail.** The familiar rule — a node is a duplication when its "
          "species mapping equals a child's — is only valid on a *binary* "
          "tree. Under the support-collapsed variant the root of the "
          "vertebrate subtree becomes a four-way polytomy whose children map "
          "to Cyclostomata, Gnathostomata, Cyclostomata and Gnathostomata: no "
          "child maps to Vertebrata, so the binary rule "
          "reads it as a **speciation** and the collapse would have been "
          "reported as the duplications disappearing. The rule used is the "
          "standard generalisation (Vernot et al. 2008) — a duplication when a "
          "child maps to M(v) itself, or when two children land in the same "
          "child-subtree of M(v). `s13_test_recon.py` T2/T3 are the positive "
          "and negative halves of it.", ""]
    L += ["**Tips are labelled by the tree, never by the census.** A tip's "
          "paralog is the S7 extended paralog clade that holds it, read out of "
          "S7's committed `paralog_clades.tsv` rather than re-derived (T14 "
          "fails if the sets differ in size from S7's), and a tip inside none "
          "of the three is `unplaced` — it is never assigned by a database "
          "name. Species keys go through `s6_lib.binomial`, because the census "
          "carries *Latimeria chalumnae* from the genome sweep and *Latimeria "
          "chalumnae (Coelacanth)* from UniProt and a raw-string key makes "
          "that two species (T9).", ""]
    if summ:
        cells = [r for r in summ if not r.get("note")]
        skipped = [r for r in summ if r.get("note")]
        L += [f"The analysis is a **matrix**, not a single tree: "
              f"{len({r['topology'] for r in summ})} topologies x "
              f"{len(par.get('variants', []))} variants = {len(cells)} "
              f"reconciliations run"
              + (f" and {len(skipped)} refused" if skipped else "") + ".", ""]
        L += table(["topology", "what it is"],
                   [[f"`{k}`", v] for k, v in
                    par.get("topologies", {}).items()])
        L += ["| variant | what it removes |", "|---|---|",
              "| `with_cyclostome` | nothing — all 57 vertebrate tips |",
              "| `without_cyclostome` | the six cyclostome loci, **actually "
              "pruned** rather than filtered out of a wanted set: a tip that "
              "is still in the tree still maps to a species and still counts "
              "(T5) |",
              "| `support_collapsed` | every internal edge below S7's own bar "
              "(SH-aLRT ≥ 80 **and** UFBoot ≥ 95), dissolved into a polytomy |",
              ""]
        if skipped:
            L += ["The three constrained topologies refuse the "
                  "`support_collapsed` variant, and the refusal is the point: "
                  "a constrained IQ-TREE search writes **no support values**, "
                  "so every node of such a tree reads as unsupported. The "
                  "first run of this variant dissolved all three constrained "
                  "trees into a single 134-tip polytomy and reported it as a "
                  "collapse of 40 nodes. `collapse_unsupported` now refuses a "
                  "tree carrying no support labels (T6) — grading an "
                  "*unmeasured* support as a failing one is the same error "
                  "`s7_bnni.py` refuses when it compares a constrained tree on "
                  "topology alone.", ""]
    return L


def section_selftest(meta: dict) -> list:
    st = meta.get("self_test", {})
    L = ["## 4. The negative controls", ""]
    if not st:
        return L + not_run("the self-test record")
    L += [f"`s13_test_recon.py` runs **{st.get('n_groups', 0)} groups of "
          f"constructed controls** before anything is written "
          f"(`s5_bait_screen.self_test()`'s pattern), and the driver refuses "
          f"to write if any fails. Status: "
          f"**{'passed' if st.get('passed') else 'FAILED'}**.", ""]
    L += ["Every rule in a reconciliation returns a perfectly plausible number "
          "when it is wrong, so the controls are checks on **refusal** and on "
          "the cases that separate a correct rule from a rule that merely "
          "runs:", ""]
    L += table(["control", "what must happen"], [
        ["**T2/T3**", "a polytomy whose children coexist in one ancestor is a "
                      "duplication; one whose children occupy distinct "
                      "subtrees is not"],
        ["**T4**", "`extract_clade` refuses a clade that also holds a tip "
                   "outside the requested set"],
        ["**T5**", "pruning actually removes the tip and leaves no unary node"],
        ["**T6**", "the support collapse refuses a tree with no support "
                   "labels"],
        ["**T7**", "the collapse takes exactly the nodes below the bar and "
                   "leaves those above"],
        ["**T8**", "rerooting at every edge preserves every tip and leaves no "
                   "unary node"],
        ["**T9**", "one species under two spellings maps to one species-tree "
                   "tip"],
        ["**T10**", "each of the ten loss verdicts fires on its own case — "
                    "including both halves of the rule that stops a "
                    "bait-panel limit reading as a gene loss"],
        ["**T11**", "four hand-derived Zmasek & Eddy loss counts, because a "
                    "factor-of-two error in that formula looks exactly like a "
                    "real result"],
        ["**T12**", "the species-tree validator can *fail* — on a missing "
                    "calibration, an age inversion and a stem age younger "
                    "than its crown"],
        ["**T13**", "two reconciliations of identical input agree"],
        ["**T14**", "the paralog clade sets are the ones S7 committed"],
    ])
    L += ["Mutation-tested on three deliberate rule breakages — reverting to "
          "the binary duplication test, dropping the `paralog_unassignable` "
          "rule, and letting the collapse run on an unlabelled tree — all "
          "three caught.", "",
          f"`reconciliation_stats.json` records the parameters above, the "
          f"self-test status and the SHA-256 of every committed table, so a "
          f"rerun that drifts is visible in the data rather than only in a "
          f"diff.", ""]
    return L


def main() -> int:
    meta = load_json("reconciliation_stats.json")
    cal = load("species_tree_calibrations.tsv")
    summ = load("reconciliation_summary.tsv")
    L = section_head(cal, summ)
    L += section_species_tree(cal)
    L += section_instrument(meta, summ)
    L += section_selftest(meta)
    import s13_report_results as res
    L += res.render(load=load, load_json=load_json, table=table, num=num,
                    not_run=not_run, meta=meta)
    out = OUT / "report.md"
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out} ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
