"""S14 claims — constraint, structure, the clinical variants and the annotation audit.

One row per load-bearing number in that part of the manuscript, naming the
committed table it comes from and the operation that recovers it (D12).
Imported and concatenated by `s14_claims.py`, which owns the engine; the
ledger is split across three modules only to keep every file inside the
project's 500-line budget.

  op:   count | cell | nunique | sum | json | grep
  where keys support `col`, `col__startswith`, `col__in` (comma-separated).

`grep` is used where a number is a join or a ratio the other ops cannot
express. It is not a weaker check: the reports it reads are themselves
rendered from the committed tables by script and carry no hand-written
numbers (D13), so a grep row still fails if the data move.
"""

from __future__ import annotations

CLAIMS: list[dict] = [

    # ------------------------------------------------- R5: the machine
    dict(id="C115", section="R5",
         claim="the deep layer holds 264 ITPR1 orthologues",
         source="results/constraint/layer_sizes.tsv", op="cell",
         where={"layer": "deep", "paralog": "ITPR1"}, column="n_sequences",
         expect="264"),
    dict(id="C116", section="R5",
         claim="249 for ITPR2",
         source="results/constraint/layer_sizes.tsv", op="cell",
         where={"layer": "deep", "paralog": "ITPR2"}, column="n_sequences",
         expect="249"),
    dict(id="C117", section="R5",
         claim="265 for ITPR3",
         source="results/constraint/layer_sizes.tsv", op="cell",
         where={"layer": "deep", "paralog": "ITPR3"}, column="n_sequences",
         expect="265"),
    dict(id="C118", section="R5",
         claim="the family layer holds all 128 ITPR tips",
         source="results/constraint/layer_sizes.tsv", op="cell",
         where={"layer": "family"}, column="n_sequences", expect="128"),
    dict(id="C119", section="R5",
         claim="the ITPR1 gate has a mean JSD of 0.799",
         source="results/constraint/constraint_by_element.tsv", op="cell",
         where={"paralog": "ITPR1", "element": "gate"}, column="mean_jsd",
         expect="0.7994", tol=1e-4),
    dict(id="C120", section="R5",
         claim="the ITPR1 linker control mean is 0.726",
         source="results/constraint/constraint_by_element.tsv", op="cell",
         where={"paralog": "ITPR1", "element": "gate"},
         column="control_mean_jsd", expect="0.7256", tol=1e-4),
    dict(id="C121", section="R5",
         claim="the ITPR1 luminal loop has a mean JSD of 0.488",
         source="results/constraint/constraint_by_element.tsv", op="cell",
         where={"paralog": "ITPR1", "element": "luminal_loop"},
         column="mean_jsd", expect="0.4883", tol=1e-4),
    dict(id="C122", section="R5",
         claim="the luminal loop is 49 residues in ITPR1",
         source="results/constraint/constraint_by_element.tsv", op="cell",
         where={"paralog": "ITPR1", "element": "luminal_loop"},
         column="n_sites", expect="49"),
    dict(id="C123", section="R5",
         claim="RIH-associated is the most constrained domain in ITPR1",
         source="results/constraint/constraint_by_element.tsv", op="cell",
         where={"paralog": "ITPR1", "element": "RIH_assoc"},
         column="mean_jsd", expect="0.8037", tol=1e-4),
    dict(id="C124", section="R5",
         claim="the ten IP3 contacts lie in MIR and RIH_N, not PF08709",
         source="results/constraint/functional_site_constraint.tsv", op="cell",
         where={"paralog": "ITPR1", "site_class": "ip3_contact"},
         column="elements", expect="MIR;RIH_N"),
    dict(id="C125", section="R5",
         claim="they beat the whole ITPR1 protein at p = 0.013",
         source="results/constraint/functional_site_constraint.tsv", op="cell",
         where={"paralog": "ITPR1", "site_class": "ip3_contact"},
         column="p_greater_than_protein", expect="0.013", tol=1e-4),
    dict(id="C126", section="R5",
         claim="and the whole ITPR2 protein at p = 6e-04",
         source="results/constraint/functional_site_constraint.tsv", op="cell",
         where={"paralog": "ITPR2", "site_class": "ip3_contact"},
         column="p_greater_than_protein", expect="0.0006", tol=1e-5),
    dict(id="C127", section="R5",
         claim="1,753 ClinVar missense records were placed",
         source="results/constraint/variants.tsv", op="count",
         where={"source": "clinvar"}, expect="1753"),
    dict(id="C128", section="R5",
         claim="1,546 of them are variants of uncertain significance",
         source="results/constraint/variants.tsv", op="count",
         where={"source": "clinvar", "class_bucket": "VUS"}, expect="1546"),
    dict(id="C129", section="R5",
         claim="the family layer is the best classifier (AUC 0.872)",
         source="results/constraint/variant_constraint_test.tsv", op="cell",
         where={"gene": "POOLED", "layer": "family",
                "contrast": "P/LP vs B/LB, all layers scorable"},
         column="auc", expect="0.8723", tol=1e-4),
    dict(id="C130", section="R5",
         claim="the vertebrate layer reaches 0.854",
         source="results/constraint/variant_constraint_test.tsv", op="cell",
         where={"gene": "POOLED", "layer": "vert",
                "contrast": "P/LP vs B/LB, all layers scorable"},
         column="auc", expect="0.8536", tol=1e-4),
    dict(id="C131", section="R5",
         claim="the deep layer only 0.758",
         source="results/constraint/variant_constraint_test.tsv", op="cell",
         where={"gene": "POOLED", "layer": "deep",
                "contrast": "P/LP vs B/LB, all layers scorable"},
         column="auc", expect="0.758", tol=1e-3),
    dict(id="C132", section="R5",
         claim="the shallow control 0.684",
         source="results/constraint/variant_constraint_test.tsv", op="cell",
         where={"gene": "POOLED", "layer": "shallow",
                "contrast": "P/LP vs B/LB, all layers scorable"},
         column="auc", expect="0.6842", tol=1e-4),
    dict(id="C133", section="R5",
         claim="the contrast rests on 44 pathogenic positions",
         source="results/constraint/variant_constraint_test.tsv", op="cell",
         where={"gene": "POOLED", "layer": "family",
                "contrast": "P/LP vs B/LB, all layers scorable"},
         column="n_positive", expect="44"),
    dict(id="C134", section="R5",
         claim="and 34 benign ones",
         source="results/constraint/variant_constraint_test.tsv", op="cell",
         where={"gene": "POOLED", "layer": "family",
                "contrast": "P/LP vs B/LB, all layers scorable"},
         column="n_negative", expect="34"),
    dict(id="C135", section="R5",
         claim="FEL finds 5,766 purifying sites across the three paralogues",
         source="results/constraint/fel_status.tsv", op="sum",
         column="n_purifying_q05", expect="5766"),
    dict(id="C136", section="R5",
         claim="and one diversifying site",
         source="results/constraint/fel_status.tsv", op="sum",
         column="n_diversifying_q05", expect="1"),
    dict(id="C137", section="R5",
         claim="AlphaFold covers 20.9 % of UniProt-shaped census records",
         source="results/structures/afdb_coverage_summary.tsv", op="cell",
         where={"scope": "census", "group": "ALL"}, column="usable_fraction",
         expect="0.209", tol=1e-3),
    dict(id="C138", section="R5",
         claim="9 of the 134 representatives have a usable model",
         source="results/structures/afdb_coverage_summary.tsv", op="cell",
         where={"scope": "reps", "group": "ALL"}, column="usable_ge_95pct",
         expect="9"),
    dict(id="C139", section="R5",
         claim="13 of 5,861 full-length census records do (0.2 %)",
         source="results/structures/report.md", op="grep",
         expect="**13** (0.2 %) have a usable model"),
    dict(id="C140", section="R5",
         claim="20 of 20 callable structures agree with the census call",
         source="results/structures/report.md", op="grep",
         expect="(20/20), and no negative control is called at all (0/3)"),
    dict(id="C141", section="R5",
         claim="the IP3-binding core is the best-modelled domain (pLDDT 83.9)",
         source="results/structures/plddt_summary.tsv", op="cell",
         where={"pfam": "PF08709"}, column="median_plddt", expect="83.88",
         tol=0.02),
    dict(id="C142", section="R5",
         claim="the pore the worst (71.0)",
         source="results/structures/plddt_summary.tsv", op="cell",
         where={"pfam": "PF00520"}, column="median_plddt", expect="71.01",
         tol=0.02),
    dict(id="C143", section="R5",
         claim="against 69.5 outside annotated domains",
         source="results/structures/plddt_summary.tsv", op="cell",
         where={"label": "outside annotated domains"}, column="median_plddt",
         expect="69.50", tol=0.02),

    # --------------------------------------------- R6: the annotation
    dict(id="C144", section="R6",
         claim="73.9 % of IP3 receptor loci are complete",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.frac_itpr_complete", expect="0.7393",
         tol=1e-4),
    dict(id="C145", section="R6",
         claim="the ryanodine receptor control is 77.9 %",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.frac_control_complete", expect="0.7792",
         tol=1e-4),
    dict(id="C146", section="R6",
         claim="no overall difference survives BH over all scorable loci",
         source="results/annotation_audit/family_vs_control.tsv", op="cell",
         where={"scope": "all scorable loci",
                "measure": "any annotation failure"}, column="q_bh",
         expect="0.127691", tol=1e-5),
    dict(id="C147", section="R6",
         claim="nor above the contiguity bar",
         source="results/annotation_audit/family_vs_control.tsv", op="cell",
         where={"scope": "loci on a contig that spans the gene (D4)",
                "measure": "any annotation failure"}, column="q_bh",
         expect="0.819481", tol=1e-5),
    dict(id="C148", section="R6",
         claim="42 ITPR loci are held only by a non-coding feature",
         source="results/annotation_audit/family_vs_control.tsv", op="cell",
         where={"scope": "all scorable loci", "measure": "noncoding"},
         column="n_itpr_failing", expect="42"),
    dict(id="C149", section="R6",
         claim="against 16 RyR loci (q = 0.006)",
         source="results/annotation_audit/family_vs_control.tsv", op="cell",
         where={"scope": "all scorable loci", "measure": "noncoding"},
         column="n_ryr_failing", expect="16"),
    dict(id="C150", section="R6",
         claim="but 4 against 5 above the bar (q = 1.0)",
         source="results/annotation_audit/family_vs_control.tsv", op="cell",
         where={"scope": "loci on a contig that spans the gene (D4)",
                "measure": "noncoding"}, column="q_bh", expect="1", tol=1e-6),
    dict(id="C151", section="R6",
         claim="RefSeq annotations are 98.8 % complete",
         source="results/annotation_audit/by_source.tsv", op="cell",
         where={"scope": "all scorable loci", "state": "complete"},
         column="frac_refseq", expect="0.9881", tol=1e-4),
    dict(id="C152", section="R6",
         claim="GenBank annotations 37.5 %",
         source="results/annotation_audit/by_source.tsv", op="cell",
         where={"scope": "all scorable loci", "state": "complete"},
         column="frac_genbank", expect="0.3748", tol=1e-4),
    dict(id="C153", section="R6",
         claim="above the contiguity bar, 99.4 % against 63.8 %",
         source="results/annotation_audit/by_source.tsv", op="cell",
         where={"scope": "loci on a contig that spans the gene (D4)",
                "state": "complete"}, column="frac_genbank", expect="0.6378",
         tol=1e-4),
    dict(id="C154", section="R6",
         claim="the ITPR failure rate falls to 6.7 % above the bar",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.frac_itpr_failure_above_d4",
         expect="0.0669", tol=1e-4),
    dict(id="C155", section="R6",
         claim="the completeness bar sits at the 1.3 % point of 1,077 loci",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.calibration_frac_below_bar",
         expect="0.013", tol=1e-4),
    dict(id="C156", section="R6",
         claim="whose median single-model coverage is 0.993",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.calibration_median", expect="0.993",
         tol=1e-4),
    dict(id="C157", section="R6",
         claim="11,402 full-length family protein records were scored",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_protein_records", expect="11402"),
    dict(id="C158", section="R6",
         claim="4 disagree with the census on family by sequence",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_protein_seq_family_disagrees",
         expect="4"),
    dict(id="C159", section="R6",
         claim="52 of 8,306 vertebrate symbols name the wrong paralogue",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_symbol_wrong_paralog", expect="52"),
    dict(id="C160", section="R6",
         claim="3,872 records carry a placeholder symbol",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_symbol_placeholder", expect="3872"),
    dict(id="C161", section="R6",
         claim="2,395 carry none at all",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_symbol_absent", expect="2395"),
    dict(id="C162", section="R6",
         claim="all 15 zero-hit reference proteomes are gene-caller failures",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_zero_hit_gene_caller", expect="15"),
    dict(id="C163", section="R6",
         claim="the audit produced 297 corrections",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_corrections", expect="297"),
    dict(id="C164", section="R6",
         claim="52 of them high priority",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_corrections_high", expect="52"),
    dict(id="C165", section="R6",
         claim="18 withheld with the reason recorded",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_corrections_vetoed", expect="18"),
    dict(id="C166", section="R6",
         claim="382 loci pass the five eligibility rules",
         source="results/annotation_bugs/case_ranking.tsv", op="count",
         where={"eligible": "True"}, expect="382"),
    dict(id="C167", section="R6",
         claim="the annotation gets 375 of them right (98.2 %)",
         source="results/annotation_bugs/report.md", op="grep",
         expect="at **375** of those (98.2 %) it did"),
    dict(id="C168", section="R6",
         claim="940 of 1,232 demonstrated genes are unreachable by protein search",
         source="results/methods/methods_stats.json", op="json",
         key="headline.gene_recovery.invisible", expect="940"),
    dict(id="C169", section="R6",
         claim="out of 1,232 genes",
         source="results/methods/methods_stats.json", op="json",
         key="headline.gene_recovery.n_genes", expect="1232"),
    dict(id="C170", section="R6",
         claim="386 of them are in species with no reference proteome",
         source="results/methods/methods_stats.json", op="json",
         key="headline.gene_recovery.by_channel.genome_only:no_reference_proteome",
         expect="386"),
    dict(id="C171", section="R6",
         claim="74.3 % for order representatives",
         source="results/methods/methods_stats.json", op="json",
         key="headline.gene_recovery.by_scope.order representative",
         expect="0.7428", tol=1e-4),
    dict(id="C172", section="R6",
         claim="78.5 % for margin species",
         source="results/methods/methods_stats.json", op="json",
         key="headline.gene_recovery.by_scope.margin species",
         expect="0.7855", tol=1e-4),
    dict(id="C173", section="R6",
         claim="67 public RNA-seq runs were quantified",
         source="results/expression/expression_stats.json", op="json",
         key="runs_quantified", expect="67"),
    dict(id="C174", section="R6",
         claim="298 of 314 unmodelled junctions are crossed by reads",
         source="results/expression/report.md", op="grep",
         expect="298 of 314 (94.9 %) junctions no annotated model spans"),
    dict(id="C175", section="R6",
         claim="the cross-mapping control is exactly zero",
         source="results/expression/expression_stats.json", op="json",
         key="crossmap_worst_rate", expect="0.0", tol=1e-9),
    # S24 — the supplementary section's four load-bearing numbers. All four
    # are the *scale of a guard*, which is exactly the kind of number a
    # reader has to be able to check: a column walk over a sample and a
    # column walk over everything read the same in prose.
    dict(id="C176", section="Supplementary",
         claim="the column walk covered all 1,797 trimmed columns",
         source="results/supplementary/supplementary_stats.json", op="json",
         key="guards.columns_checked", expect="1797"),
    dict(id="C177", section="Supplementary",
         claim="the column walk covered all 134 sequences",
         source="results/supplementary/supplementary_stats.json", op="json",
         key="guards.sequences", expect="134"),
    dict(id="C178", section="Supplementary",
         claim="1,780 variant residues were checked against their own table",
         source="results/supplementary/supplementary_stats.json", op="json",
         key="guards.variant_residues_checked", expect="1780"),
    dict(id="C179", section="Supplementary",
         claim="2,699 aligned partners were checked",
         source="results/supplementary/supplementary_stats.json", op="json",
         key="guards.aligned_partners_checked", expect="2699"),
    dict(id="C180", section="Supplementary",
         claim="AlphaFold DB's human ITPR1 model is the 2,695-residue "
               "Q14643-4 isoform",
         source="results/supplementary/supplementary_stats.json", op="json",
         key="headline.itpr1_afdb_model_residues", expect="2695"),
    # ------------------------------- R5: the ligand core against the pore
    dict(id="C222", section="R5",
         claim="the pocket was measured in 6 independent IP3-bound structures",
         source="results/ligand_site/shell_agreement.tsv", op="count", expect="6"),
    dict(id="C223", section="R5",
         claim="6DQN recovers all ten published contacts",
         source="results/ligand_site/shell_agreement.tsv", op="cell",
         where={"pdb_id": "6DQN"}, column="n_s0_contacts_recovered",
         expect="10"),
    dict(id="C224", section="R5",
         claim="8TKG recovers all ten and adds two",
         source="results/ligand_site/shell_agreement.tsv", op="cell",
         where={"pdb_id": "8TKG"}, column="extra_contacts", expect="276;411"),
    dict(id="C225", section="R5",
         claim="the contacts beat the rest of the core in ITPR1 (q = 0.048)",
         source="results/ligand_site/contact_test.tsv", op="cell",
         where={"contact_set": "s0_contact", "background": "rest_of_core",
                "paralog": "ITPR1", "layer": "deep"},
         column="q_permutation", expect="0.048", tol=1e-3),
    dict(id="C226", section="R5",
         claim="in ITPR2 (q = 0.017)",
         source="results/ligand_site/contact_test.tsv", op="cell",
         where={"contact_set": "s0_contact", "background": "rest_of_core",
                "paralog": "ITPR2", "layer": "deep"},
         column="q_permutation", expect="0.01725", tol=1e-3),
    dict(id="C227", section="R5",
         claim="in ITPR3 (q = 0.041)",
         source="results/ligand_site/contact_test.tsv", op="cell",
         where={"contact_set": "s0_contact", "background": "rest_of_core",
                "paralog": "ITPR3", "layer": "deep"},
         column="q_permutation", expect="0.041324", tol=1e-3),
    dict(id="C228", section="R5",
         claim="and beat the rest of the pocket in none - ITPR2 is the "
               "smallest q at 0.12",
         source="results/ligand_site/contact_test.tsv", op="cell",
         where={"contact_set": "s0_contact", "background": "rest_of_pocket",
                "paralog": "ITPR2", "layer": "deep"},
         column="q_permutation", expect="0.124893", tol=1e-3),
    dict(id="C229", section="R5",
         claim="every ITPR1 contact site is under purifying selection",
         source="results/ligand_site/omega_by_shell.tsv", op="cell",
         where={"paralog": "ITPR1", "shell": "contact"},
         column="frac_purifying_q05", expect="1.0", tol=1e-9),
    dict(id="C230", section="R5",
         claim="and every ITPR3 contact site",
         source="results/ligand_site/omega_by_shell.tsv", op="cell",
         where={"paralog": "ITPR3", "shell": "contact"},
         column="frac_purifying_q05", expect="1.0", tol=1e-9),
    dict(id="C231", section="R5",
         claim="falling to 0.875 in ITPR1's lowest shell, a fall of 0.13",
         source="results/ligand_site/omega_by_shell.tsv", op="cell",
         where={"paralog": "ITPR1", "shell": "third"},
         column="frac_purifying_q05", expect="0.875", tol=1e-4),
    dict(id="C232", section="R5",
         claim="to 0.750 in ITPR2's, a fall of 0.25",
         source="results/ligand_site/omega_by_shell.tsv", op="cell",
         where={"paralog": "ITPR2", "shell": "third"},
         column="frac_purifying_q05", expect="0.75", tol=1e-4),
    dict(id="C232b", section="R5",
         claim="and to 0.825 in ITPR3's, a fall of 0.18",
         source="results/ligand_site/omega_by_shell.tsv", op="cell",
         where={"paralog": "ITPR3", "shell": "third"},
         column="frac_purifying_q05", expect="0.825", tol=1e-4),
    dict(id="C232c", section="R5",
         claim="the outermost shell sits above the third in ITPR1, so the "
               "fall is not monotone",
         source="results/ligand_site/omega_by_shell.tsv", op="cell",
         where={"paralog": "ITPR1", "shell": "fourth"},
         column="frac_purifying_q05", expect="0.8966", tol=1e-3),
    dict(id="C233", section="R5",
         claim="the ITPR1 pore leads the core by 0.0239 identity",
         source="results/ligand_site/module_contrast.tsv", op="cell",
         where={"paralog": "ITPR1", "is_primary": "True"},
         column="mean_difference", expect="-0.0239", tol=1e-4),
    dict(id="C234", section="R5",
         claim="on 223 tips against 32",
         source="results/ligand_site/module_contrast.tsv", op="cell",
         where={"paralog": "ITPR1", "is_primary": "True"},
         column="n_pore_more_conserved", expect="223"),
    dict(id="C235", section="R5",
         claim="at q = 3.6e-34",
         source="results/ligand_site/module_contrast.tsv", op="cell",
         where={"paralog": "ITPR1", "is_primary": "True"},
         column="q_wilcoxon", expect="3.64188e-34", tol=1e-36),
    dict(id="C236", section="R5",
         claim="the ITPR3 pore leads by 0.0199",
         source="results/ligand_site/module_contrast.tsv", op="cell",
         where={"paralog": "ITPR3", "is_primary": "True"},
         column="mean_difference", expect="-0.0199", tol=1e-4),
    dict(id="C237", section="R5",
         claim="on 218 tips against 42",
         source="results/ligand_site/module_contrast.tsv", op="cell",
         where={"paralog": "ITPR3", "is_primary": "True"},
         column="n_pore_more_conserved", expect="218"),
    dict(id="C238", section="R5",
         claim="ITPR2 shows no difference (q = 0.13)",
         source="results/ligand_site/module_contrast.tsv", op="cell",
         where={"paralog": "ITPR2", "is_primary": "True"},
         column="q_wilcoxon", expect="0.134144", tol=1e-4),
    dict(id="C239", section="R5",
         claim="the paired test runs on 260 ITPR1 orthologues",
         source="results/ligand_site/module_contrast.tsv", op="cell",
         where={"paralog": "ITPR1", "is_primary": "True"},
         column="n_tips", expect="260"),
    dict(id="C240", section="R5",
         claim="246 ITPR2",
         source="results/ligand_site/module_contrast.tsv", op="cell",
         where={"paralog": "ITPR2", "is_primary": "True"},
         column="n_tips", expect="246"),
    dict(id="C241", section="R5",
         claim="262 ITPR3",
         source="results/ligand_site/module_contrast.tsv", op="cell",
         where={"paralog": "ITPR3", "is_primary": "True"},
         column="n_tips", expect="262"),
    dict(id="C242", section="R5",
         claim="with the luminal loop left in, ITPR1 reverses to core > pore "
               "by 0.055",
         source="results/ligand_site/module_contrast.tsv", op="cell",
         where={"paralog": "ITPR1", "core_definition": "contact_span",
                "pore_definition": "channel_all"},
         column="mean_difference", expect="0.055", tol=1e-4),
    dict(id="C243", section="R5",
         claim="ITPR2 by 0.0445",
         source="results/ligand_site/module_contrast.tsv", op="cell",
         where={"paralog": "ITPR2", "core_definition": "contact_span",
                "pore_definition": "channel_all"},
         column="mean_difference", expect="0.0445", tol=1e-4),
    dict(id="C244", section="R5",
         claim="ITPR3 by 0.0558",
         source="results/ligand_site/module_contrast.tsv", op="cell",
         where={"paralog": "ITPR3", "core_definition": "contact_span",
                "pore_definition": "channel_all"},
         column="mean_difference", expect="0.0558", tol=1e-4),
    dict(id="C245", section="R5",
         claim="the worst of the three reversed q values is 1.5e-41",
         source="results/ligand_site/module_contrast.tsv", op="cell",
         where={"paralog": "ITPR1", "core_definition": "contact_span",
                "pore_definition": "channel_all"},
         column="q_wilcoxon", expect="1.53085e-41", tol=1e-43),
    dict(id="C246", section="R5",
         claim="3,527 eukaryotic reference proteomes were swept for PI-PLC",
         source="results/ligand_site/plc_repertoire.tsv", op="count", expect="3527"),
    dict(id="C247", section="R5",
         claim="64 of them carry an ITPR and no PI-PLC",
         source="results/ligand_site/pathway_cooccurrence.tsv", op="sum",
         column="n_itpr_no_plc", expect="64"),
    dict(id="C248", section="R5",
         claim="no vertebrate proteome does - the search's positive control",
         source="results/ligand_site/pathway_cooccurrence.tsv", op="cell",
         where={"group": "vertebrata"}, column="n_itpr_no_plc", expect="0"),
    dict(id="C249", section="R5",
         claim="PLC-absent records sit at a median pore identity of 0.358",
         source="results/ligand_site/deep_lineage_covariates.tsv", op="cell",
         where={"covariate": "pore_identity"}, column="median_plc_absent",
         expect="0.3582", tol=1e-4),
    dict(id="C250", section="R5",
         claim="against 0.589 for the rest",
         source="results/ligand_site/deep_lineage_covariates.tsv", op="cell",
         where={"covariate": "pore_identity"}, column="median_plc_present",
         expect="0.5886", tol=1e-4),
    dict(id="C251", section="R5",
         claim="all 36 PLC-absent records matched on divergence",
         source="results/ligand_site/deep_lineage_matched_summary.tsv", op="cell",
         where={}, column="n_matched", expect="36"),
    dict(id="C252", section="R5",
         claim="the matched within-pair difference is -0.0064",
         source="results/ligand_site/deep_lineage_matched_summary.tsv", op="cell",
         where={}, column="median_difference", expect="-0.0064", tol=1e-4),
    dict(id="C253", section="R5",
         claim="95 % CI -0.0161",
         source="results/ligand_site/deep_lineage_matched_summary.tsv", op="cell",
         where={}, column="ci95_lo", expect="-0.0161", tol=1e-4),
    dict(id="C254", section="R5",
         claim="to 0.0152",
         source="results/ligand_site/deep_lineage_matched_summary.tsv", op="cell",
         where={}, column="ci95_hi", expect="0.0152", tol=1e-4),
    dict(id="C255", section="R5",
         claim="19 tips against 17",
         source="results/ligand_site/deep_lineage_matched_summary.tsv", op="cell",
         where={}, column="n_core_more_relaxed", expect="19"),
    dict(id="C256", section="R5",
         claim="p = 0.87 on the sign test",
         source="results/ligand_site/deep_lineage_matched_summary.tsv", op="cell",
         where={}, column="p_sign", expect="0.867939", tol=1e-4),
    dict(id="C257", section="R5",
         claim="the ryanodine receptor control shifts by -0.0624 on the "
               "same instrument",
         source="results/ligand_site/deep_lineage_ryr_control.tsv", op="grep",
         expect="-0.0624"),
    dict(id="C258", section="R5",
         claim="the matched test has 0.99 power at a shift of 0.05",
         source="results/ligand_site/deep_lineage_matched_power.tsv", op="cell",
         where={"shift": "0.05"}, column="power", expect="0.9902", tol=1e-3),
    dict(id="C259", section="R5",
         claim="and 0.59 at 0.03",
         source="results/ligand_site/deep_lineage_matched_power.tsv", op="cell",
         where={"shift": "0.03"}, column="power", expect="0.5877", tol=1e-3),

    # ------------------------- R6: where a fragmentary annotation stops (S21)
    dict(id="C260", section="R6",
         claim="291 split or fragmentary loci were scored",
         source="results/gene_architecture/gene_architecture_stats.json", op="json",
         key="headline.fragments.n_loci", expect="291"),
    dict(id="C261", section="R6",
         claim="264 of them are fragmentary",
         source="results/gene_architecture/gene_architecture_stats.json", op="json",
         key="headline.fragments_by_state.fragmentary.n_loci", expect="264"),
    dict(id="C262", section="R6",
         claim="27 are split",
         source="results/gene_architecture/gene_architecture_stats.json", op="json",
         key="headline.fragments_by_state.split.n_loci", expect="27"),
    dict(id="C263", section="R6",
         claim="228 carry a terminus inside an exon",
         source="results/gene_architecture/gene_architecture_stats.json", op="json",
         key="headline.fragments.annotation_failure", expect="228"),
    dict(id="C264", section="R6",
         claim="3 are broken entirely at real junctions",
         source="results/gene_architecture/gene_architecture_stats.json", op="json",
         key="headline.fragments.broken_at_real_junctions", expect="3"),
    dict(id="C265", section="R6",
         claim="1,448 internal termini were scored",
         source="results/gene_architecture/gene_architecture_stats.json", op="json",
         key="headline.fragments.internal_termini", expect="1448"),
    dict(id="C266", section="R6",
         claim="406 of them sit inside an exon",
         source="results/gene_architecture/gene_architecture_stats.json", op="json",
         key="headline.fragments.termini_mid_exon", expect="406"),
    dict(id="C267", section="R6",
         claim="353 inside an intron",
         source="results/gene_architecture/gene_architecture_stats.json", op="json",
         key="headline.fragments.termini_in_intron", expect="353"),
    dict(id="C268", section="R6",
         claim="689 on a boundary the gene model carries",
         source="results/gene_architecture/gene_architecture_stats.json", op="json",
         key="headline.fragments.termini_at_exon_boundary", expect="689"),
    dict(id="C269", section="R6",
         claim="which is 47.6 % of them",
         source="results/gene_architecture/gene_architecture_stats.json", op="json",
         key="headline.fragments.frac_termini_at_boundary",
         expect="0.4758", tol=1e-4),
]
