"""S14 claims — the search space, the family's range, and the vertebrate census.

One row per load-bearing number in that part of the manuscript, naming the
committed table it comes from and the operation that recovers it (D12).
Imported and concatenated by `s14_claims.py`, which owns the engine; the
ledger is split across three modules only to keep every file inside the
project's 500-line budget.

  op:   count | cell | nunique | sum | json | grep
  where keys support `col`, `col__startswith`, `col__in` (comma-separated).

`grep` is used where a number is a join or a ratio the other ops cannot
express. It is not a weaker check: the reports it reads are themselves
rendered from the committed tables by script and carry no hand-written
numbers (D13), so a grep row still fails if the data move.
"""

from __future__ import annotations

CLAIMS: list[dict] = [
    # ---------------------------------------------------------- scope
    dict(id="C01", section="R2/methods",
         claim="the vertebrate genome scope is 309 assemblies",
         source="results/genome_manifest.tsv", op="nunique",
         column="accession", expect="309"),
    dict(id="C02", section="R1/methods",
         claim="the non-vertebrate genome scope is 194 assemblies",
         source="results/s23_scope/genome_manifest_s23.tsv", op="nunique",
         column="accession", expect="194"),
    dict(id="C03", section="R1",
         claim="6,928 non-vertebrate reference proteomes were swept",
         source="results/s20_sweep/proteome_presence.tsv", op="count",
         expect="6928"),
    dict(id="C04", section="R1/methods",
         claim="763 vertebrate reference proteomes were swept",
         source="results/hmm_sweep/proteome_db_stats.json", op="json",
         key="n_proteomes", expect="763"),
    dict(id="C05", section="R1/methods",
         claim="the vertebrate proteome sweep covered 14,414,821 proteins",
         source="results/hmm_sweep/proteome_db_stats.json", op="json",
         key="n_seqs", expect="14414821"),
    dict(id="C06", section="R1/methods",
         claim="the non-vertebrate sweep covered 63,144,898 proteins",
         source="results/s20_sweep/report.md", op="grep",
         expect="6,928 reference proteomes, 63,144,898 proteins"),
    dict(id="C07", section="R1",
         claim="the census holds 18,065 records",
         source="results/census_v6/census_v6_stats.json", op="json",
         key="census_v6_rows", expect="18065"),
    dict(id="C08", section="R1",
         claim="8,990 census records are called IP3 receptor",
         source="results/census_v6/census_v6.tsv", op="count",
         where={"call": "ITPR"}, expect="8990"),
    dict(id="C09", section="R1",
         claim="the IP3 receptor census spans 1,402 taxa",
         source="results/census_v6/census_v6.tsv", op="nunique",
         where={"call": "ITPR"}, column="taxon_id", expect="1402"),
    dict(id="C10", section="R1",
         claim="662 of 6,928 non-vertebrate proteomes carry an ITPR call",
         source="results/s20_sweep/report.md", op="grep",
         expect="**662/6,928"),

    # ---------------------------------------------------- R1: the range
    dict(id="C11", section="R1",
         claim="Streptophyta: 384 proteomes swept, 0 genomes with an ITPR",
         source="results/s23_scope/absence_at_genome.tsv", op="cell",
         where={"clade": "Streptophyta"}, column="swept_proteomes",
         expect="384"),
    dict(id="C12", section="R1",
         claim="Ascomycota: 1,034 proteomes swept",
         source="results/s23_scope/absence_at_genome.tsv", op="cell",
         where={"clade": "Ascomycota"}, column="swept_proteomes",
         expect="1034"),
    dict(id="C13", section="R1",
         claim="Basidiomycota: 319 proteomes swept",
         source="results/s23_scope/absence_at_genome.tsv", op="cell",
         where={"clade": "Basidiomycota"}, column="swept_proteomes",
         expect="319"),
    dict(id="C14", section="R1",
         claim="Apicomplexa: 60 proteomes swept",
         source="results/s23_scope/absence_at_genome.tsv", op="cell",
         where={"clade": "Apicomplexa"}, column="swept_proteomes",
         expect="60"),
    dict(id="C15", section="R1",
         claim="35 clade-level absences were taken to assembly level",
         source="results/s23_scope/absence_at_genome.tsv", op="count",
         expect="35"),
    dict(id="C16", section="R1",
         claim="all 35 absences hold at assembly level",
         source="results/s23_scope/absence_at_genome.tsv", op="count",
         where={"verdict": "absence holds at assembly level"}, expect="35"),
    dict(id="C17", section="R1",
         claim="no genome in the non-vertebrate sweep is uncontrolled",
         source="results/s23_scope/ledger_stats.json", op="json",
         key="uncontrolled", expect="0"),
    dict(id="C18", section="R1",
         claim="117 of the 194 genomes carry no IP3 receptor",
         source="results/s23_scope/ledger_stats.json", op="json",
         key="copy_number.0", expect="117"),
    dict(id="C19", section="R1",
         claim="43 of the 194 genomes carry exactly one",
         source="results/s23_scope/ledger_stats.json", op="json",
         key="copy_number.1", expect="43"),
    dict(id="C20", section="R1",
         claim="Macrostomum lignano carries 18 IP3 receptor genes",
         source="results/s23_scope/ledger_stats.json", op="json",
         key="copy_number.18", expect="1"),
    dict(id="C21", section="R1",
         claim="99 plant and fungal records were chased individually",
         source="results/s20_sweep/plant_fungal_verdicts.tsv", op="count",
         expect="99"),
    dict(id="C22", section="R1",
         claim="47 of them are real genes",
         source="results/s20_sweep/plant_fungal_verdicts.tsv", op="count",
         where={"verdict": "real_gene"}, expect="47"),
    dict(id="C23", section="R1",
         claim="52 of them are fragments",
         source="results/s20_sweep/plant_fungal_verdicts.tsv", op="count",
         where={"verdict": "fragment"}, expect="52"),
    dict(id="C24", section="R1",
         claim="none of them is a contamination suspect",
         source="results/s20_sweep/plant_fungal_verdicts.tsv", op="count",
         where={"verdict": "contaminant_suspect"}, expect="0"),

    # ------------------------------------------------- R2: the census
    dict(id="C25", section="R2",
         claim="309 of 309 genomes were swept",
         source="results/genome_ledger/ledger_stats.json", op="json",
         key="genomes_swept", expect="309"),
    dict(id="C26", section="R2",
         claim="the sweep recorded 1,236 genome x cell results",
         source="results/genome_ledger/ledger_stats.json", op="json",
         key="cells", expect="1236"),
    dict(id="C27", section="R2",
         claim="the sweep recorded 2,144 loci",
         source="results/genome_ledger/ledger_stats.json", op="json",
         key="loci_recorded", expect="2144"),
    dict(id="C28", section="R2",
         claim="the ryanodine receptor control failed in no genome",
         source="results/genome_ledger/ledger_stats.json", op="json",
         key="control_failures", expect="0"),
    dict(id="C29", section="R2",
         claim="the vertebrate scope totals 552.5 Gbp",
         source="results/genome_ledger/ledger_stats.json", op="json",
         key="total_genome_bp", expect="552535418825"),
    dict(id="C30", section="R2",
         claim="4 ledger cells were called absent",
         source="results/genome_ledger/genome_ledger.tsv", op="count",
         where={"status": "absent"}, expect="4"),
    dict(id="C31", section="R2",
         claim="all 4 are cyclostome (Hyperoartia and Myxini)",
         source="results/genome_ledger/genome_ledger.tsv", op="count",
         where={"status": "absent", "vclass__in": "Hyperoartia,Myxini"},
         expect="4"),
    dict(id="C32", section="R2",
         claim="318 IP3 receptor gene models exist only as DNA",
         source="results/census_v4/db_status_counts.tsv", op="sum",
         where={"db_status": "genome_only", "cell__in": "ITPR1,ITPR2,ITPR3"},
         column="n_loci", expect="318"),
    dict(id="C33", section="R2",
         claim="167 more sit inside an annotated gene carrying no family name",
         source="results/census_v4/db_status_counts.tsv", op="sum",
         where={"db_status": "annotated_unnamed",
                "cell__in": "ITPR1,ITPR2,ITPR3"},
         column="n_loci", expect="167"),
    dict(id="C34", section="R2",
         claim="the sweep contributed 1,058 gene models from 224 genomes",
         source="results/census_v4/census_v4_stats.json", op="json",
         key="models_collected", expect="1058"),
    dict(id="C35", section="R2",
         claim="140 of 923 assignable cells are false negatives (15.2 %)",
         source="results/methods/methods_stats.json", op="json",
         key="headline.itpr_present.n_false_negative", expect="140"),
    dict(id="C36", section="R2",
         claim="the false-negative rate is 0.1517",
         source="results/methods/methods_stats.json", op="json",
         key="headline.itpr_present.rate", expect="0.1517", tol=1e-4),
    dict(id="C37", section="R2",
         claim="the RyR sister series gives 42 of 309",
         source="results/methods/methods_stats.json", op="json",
         key="headline.ryr_sister.n_false_negative", expect="42"),
    dict(id="C38", section="R2",
         claim="the RyR sister rate is 0.1359",
         source="results/methods/methods_stats.json", op="json",
         key="headline.ryr_sister.rate", expect="0.1359", tol=1e-4),
    dict(id="C39", section="R2",
         claim="the two series are indistinguishable (Fisher p = 0.58)",
         source="results/methods/methods_stats.json", op="json",
         key="headline.itpr_vs_ryr_p", expect="0.578", tol=1e-3),
    dict(id="C40", section="R2",
         claim="the odds of finding the gene rise 8.1x per tenfold of N50",
         source="results/methods/methods_stats.json", op="json",
         key="headline.contiguity_effect.itpr_present",
         expect="OR per 10x=8.10, z=9.8"),
    dict(id="C41", section="R2",
         claim="the residual false-negative rate above D4's bar is 0.9 %",
         source="results/methods/methods_stats.json", op="json",
         key="headline.itpr_present.rate_at_d4_bar", expect="0.0089",
         tol=1e-4),
    dict(id="C42", section="R2",
         claim="the RyR residual rate above the bar is 0.0 %",
         source="results/methods/methods_stats.json", op="json",
         key="headline.ryr_sister.rate_at_d4_bar", expect="0.0", tol=1e-9),
    dict(id="C43", section="R2/methods",
         claim="the contiguity bar is 142,212 bp",
         source="results/methods/methods_stats.json", op="json",
         key="headline.d4_bar", expect="142212"),
    dict(id="C44", section="R2",
         claim="189 of 309 genomes are above the contiguity bar",
         source="results/loss_dynamics/loss_dynamics_stats.json", op="json",
         key="headline.n_genomes_above_bar", expect="189"),
    dict(id="C45", section="R2",
         claim="the ablation reproduces the ledger 1,236 of 1,236 cells",
         source="results/methods/methods_stats.json", op="json",
         key="headline.panel_cells_validated", expect="1236"),
    dict(id="C46", section="R2",
         claim="the ablation found no mismatch against the ledger",
         source="results/methods/methods_stats.json", op="json",
         key="headline.panel_validation_mismatches", expect="0"),
    dict(id="C47", section="R2",
         claim="the full 38-bait panel recovers 783 cells",
         source="results/methods/methods_stats.json", op="json",
         key="headline.panel.full38.found", expect="783"),
    dict(id="C48", section="R2",
         claim="four human baits recover 782 of them",
         source="results/methods/methods_stats.json", op="json",
         key="headline.panel.human_only.found", expect="782"),
    dict(id="C49", section="R2",
         claim="dropping ITPR1's baits costs 238 cells",
         source="results/methods/methods_stats.json", op="json",
         key="headline.panel.drop_ITPR1_baits.delta", expect="-238"),
    dict(id="C50", section="R2",
         claim="dropping ITPR3's baits costs 241 cells",
         source="results/methods/methods_stats.json", op="json",
         key="headline.panel.drop_ITPR3_baits.delta", expect="-241"),
]
