"""S14 stage `deposit` — build the archive deposit manifest.

Walks every deposited results directory, records path, size and SHA-256 for
each file, and writes:

  manuscript/deposit_manifest.tsv   one row per deposited file
  manuscript/deposit_notes.md       what is deposited, what is not, and the
                                    command that regenerates each excluded
                                    bulk-data class from its public source

The manifest is what a Zenodo (or any archive) deposit is built from, and it
is also the integrity record: a reviewer can verify any deposited table
against its checksum without re-running an analysis.
"""

from __future__ import annotations

import sys

import s14_lib as lib

MAX_SINGLE_FILE_MB = 100.0


def _iter_deposit_files():
    for name in lib.DEPOSIT_DIRS:
        base = lib.RESULTS / name
        if not base.exists():
            print(f"  MISSING dir: results/{name}", file=sys.stderr)
            continue
        for path in sorted(base.rglob("*")):
            if (path.is_file()
                    and path.suffix not in lib.DEPOSIT_SKIP_SUFFIXES
                    and path.name not in lib.DEPOSIT_SKIP_NAMES):
                yield path
    for pattern in lib.DEPOSIT_ROOT_GLOBS:
        for path in sorted(lib.RESULTS.glob(pattern)):
            if path.is_file():
                yield path
    for extra in ("PUBLICATION_ROADMAP.md", "FINDINGS.md", "SESSION_LOG.md",
                  "INTERFACE.md", "README.md", "CLAUDE.md"):
        path = lib.ROOT / extra
        if path.exists():
            yield path
    for path in sorted((lib.ROOT / "scripts").glob("*.py")):
        yield path
    for path in sorted((lib.ROOT / "manuscript").rglob("*")):
        if (path.is_file()
                and path.name != "deposit_manifest.tsv"
                and path.name not in lib.DEPOSIT_SKIP_NAMES):
            yield path


def _notes(rows: list[dict], total_bytes: int) -> str:
    by_group: dict[str, list[dict]] = {}
    for r in rows:
        by_group.setdefault(r["group"], []).append(r)
    lines = [
        "# Deposit notes",
        "",
        "Generated by `scripts/s14_deposit.py`. The companion table",
        "`deposit_manifest.tsv` carries one row per deposited file with its",
        "size and SHA-256 checksum.",
        "",
        f"**Deposit size:** {len(rows)} files, {lib.size_str(total_bytes)}.",
        "",
        "## What is deposited",
        "",
        "| group | files | size |",
        "|---|---|---|",
    ]
    for group in sorted(by_group):
        grp = by_group[group]
        lines.append(f"| `{group}` | {len(grp)} | "
                     f"{lib.size_str(sum(int(r['bytes']) for r in grp))} |")

    lines += [
        "",
        "## What is not deposited, and how to regenerate it",
        "",
        "Bulk inputs are retrievable from the public archives that already",
        "guarantee their persistence. Every one of them is addressed by an",
        "accession list that *is* deposited.",
        "",
        "| data | size | source | accession list | command |",
        "|---|---|---|---|---|",
    ]
    for name, size, source, acc, cmd in lib.BULK_EXCLUSIONS:
        lines.append(f"| {name} | {size} | {source} | `{acc}` | `{cmd}` |")

    big = [r for r in rows
           if int(r["bytes"]) > MAX_SINGLE_FILE_MB * 1024 * 1024]
    lines += [
        "",
        "## Large individual files",
        "",
    ]
    if big:
        lines += ["| file | size |", "|---|---|"]
        for r in sorted(big, key=lambda r: -int(r["bytes"])):
            lines.append(f"| `{r['path']}` | {lib.size_str(int(r['bytes']))} |")
        lines.append("")
        lines.append(f"Files above {MAX_SINGLE_FILE_MB:.0f} MB are listed so "
                     "that an archive with a per-file limit can be checked "
                     "before upload.")
    else:
        lines.append(f"None: no deposited file exceeds "
                     f"{MAX_SINGLE_FILE_MB:.0f} MB.")

    lines += [
        "",
        "## Licensing",
        "",
        "- Code: as declared in the repository.",
        "- Derived tables and figures: CC-BY 4.0.",
        "- Third-party inputs retain their own licences (UniProt CC-BY 4.0;",
        "  AlphaFold DB CC-BY 4.0; RCSB public domain; NCBI/Ensembl data as",
        "  per their terms). No third-party bulk data is redistributed here.",
        "",
    ]
    return "\n".join(lines)


def run() -> int:
    rows: list[dict] = []
    seen: set = set()
    for path in _iter_deposit_files():
        rel = path.relative_to(lib.ROOT)
        if rel in seen:
            continue
        seen.add(rel)
        rows.append({
            "path": str(rel),
            "group": lib.deposit_group(rel.parts),
            "bytes": path.stat().st_size,
            "sha256": lib.sha256(path),
        })

    total = sum(int(r["bytes"]) for r in rows)
    lib.write_tsv(lib.MS / "deposit_manifest.tsv", rows,
                  ["path", "group", "bytes", "sha256"])
    (lib.MS / "deposit_notes.md").write_text(_notes(rows, total),
                                             encoding="utf-8")
    print(f"[s14 deposit] {len(rows)} files, {lib.size_str(total)} "
          f"-> manuscript/deposit_manifest.tsv + deposit_notes.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
