"""S14 claims — constraint, structure, the clinical variants and the annotation audit.

One row per load-bearing number in that part of the manuscript, naming the
committed table it comes from and the operation that recovers it (D12).
Imported and concatenated by `s14_claims.py`, which owns the engine; the
ledger is split across three modules only to keep every file inside the
project's 500-line budget.

  op:   count | cell | nunique | sum | json | grep
  where keys support `col`, `col__startswith`, `col__in` (comma-separated).

`grep` is used where a number is a join or a ratio the other ops cannot
express. It is not a weaker check: the reports it reads are themselves
rendered from the committed tables by script and carry no hand-written
numbers (D13), so a grep row still fails if the data move.
"""

from __future__ import annotations

CLAIMS: list[dict] = [

    # ------------------------------------------------- R5: the machine
    dict(id="C115", section="R5",
         claim="the deep layer holds 264 ITPR1 orthologues",
         source="results/constraint/layer_sizes.tsv", op="cell",
         where={"layer": "deep", "paralog": "ITPR1"}, column="n_sequences",
         expect="264"),
    dict(id="C116", section="R5",
         claim="249 for ITPR2",
         source="results/constraint/layer_sizes.tsv", op="cell",
         where={"layer": "deep", "paralog": "ITPR2"}, column="n_sequences",
         expect="249"),
    dict(id="C117", section="R5",
         claim="265 for ITPR3",
         source="results/constraint/layer_sizes.tsv", op="cell",
         where={"layer": "deep", "paralog": "ITPR3"}, column="n_sequences",
         expect="265"),
    dict(id="C118", section="R5",
         claim="the family layer holds all 128 ITPR tips",
         source="results/constraint/layer_sizes.tsv", op="cell",
         where={"layer": "family"}, column="n_sequences", expect="128"),
    dict(id="C119", section="R5",
         claim="the ITPR1 gate has a mean JSD of 0.799",
         source="results/constraint/constraint_by_element.tsv", op="cell",
         where={"paralog": "ITPR1", "element": "gate"}, column="mean_jsd",
         expect="0.7994", tol=1e-4),
    dict(id="C120", section="R5",
         claim="the ITPR1 linker control mean is 0.726",
         source="results/constraint/constraint_by_element.tsv", op="cell",
         where={"paralog": "ITPR1", "element": "gate"},
         column="control_mean_jsd", expect="0.7256", tol=1e-4),
    dict(id="C121", section="R5",
         claim="the ITPR1 luminal loop has a mean JSD of 0.488",
         source="results/constraint/constraint_by_element.tsv", op="cell",
         where={"paralog": "ITPR1", "element": "luminal_loop"},
         column="mean_jsd", expect="0.4883", tol=1e-4),
    dict(id="C122", section="R5",
         claim="the luminal loop is 49 residues in ITPR1",
         source="results/constraint/constraint_by_element.tsv", op="cell",
         where={"paralog": "ITPR1", "element": "luminal_loop"},
         column="n_sites", expect="49"),
    dict(id="C123", section="R5",
         claim="RIH-associated is the most constrained domain in ITPR1",
         source="results/constraint/constraint_by_element.tsv", op="cell",
         where={"paralog": "ITPR1", "element": "RIH_assoc"},
         column="mean_jsd", expect="0.8037", tol=1e-4),
    dict(id="C124", section="R5",
         claim="the ten IP3 contacts lie in MIR and RIH_N, not PF08709",
         source="results/constraint/functional_site_constraint.tsv", op="cell",
         where={"paralog": "ITPR1", "site_class": "ip3_contact"},
         column="elements", expect="MIR;RIH_N"),
    dict(id="C125", section="R5",
         claim="they beat the whole ITPR1 protein at p = 0.013",
         source="results/constraint/functional_site_constraint.tsv", op="cell",
         where={"paralog": "ITPR1", "site_class": "ip3_contact"},
         column="p_greater_than_protein", expect="0.013", tol=1e-4),
    dict(id="C126", section="R5",
         claim="and the whole ITPR2 protein at p = 6e-04",
         source="results/constraint/functional_site_constraint.tsv", op="cell",
         where={"paralog": "ITPR2", "site_class": "ip3_contact"},
         column="p_greater_than_protein", expect="0.0006", tol=1e-5),
    dict(id="C127", section="R5",
         claim="1,753 ClinVar missense records were placed",
         source="results/constraint/variants.tsv", op="count",
         where={"source": "clinvar"}, expect="1753"),
    dict(id="C128", section="R5",
         claim="1,546 of them are variants of uncertain significance",
         source="results/constraint/variants.tsv", op="count",
         where={"source": "clinvar", "class_bucket": "VUS"}, expect="1546"),
    dict(id="C129", section="R5",
         claim="the family layer is the best classifier (AUC 0.872)",
         source="results/constraint/variant_constraint_test.tsv", op="cell",
         where={"gene": "POOLED", "layer": "family",
                "contrast": "P/LP vs B/LB, all layers scorable"},
         column="auc", expect="0.8723", tol=1e-4),
    dict(id="C130", section="R5",
         claim="the vertebrate layer reaches 0.854",
         source="results/constraint/variant_constraint_test.tsv", op="cell",
         where={"gene": "POOLED", "layer": "vert",
                "contrast": "P/LP vs B/LB, all layers scorable"},
         column="auc", expect="0.8536", tol=1e-4),
    dict(id="C131", section="R5",
         claim="the deep layer only 0.758",
         source="results/constraint/variant_constraint_test.tsv", op="cell",
         where={"gene": "POOLED", "layer": "deep",
                "contrast": "P/LP vs B/LB, all layers scorable"},
         column="auc", expect="0.758", tol=1e-3),
    dict(id="C132", section="R5",
         claim="the shallow control 0.684",
         source="results/constraint/variant_constraint_test.tsv", op="cell",
         where={"gene": "POOLED", "layer": "shallow",
                "contrast": "P/LP vs B/LB, all layers scorable"},
         column="auc", expect="0.6842", tol=1e-4),
    dict(id="C133", section="R5",
         claim="the contrast rests on 44 pathogenic positions",
         source="results/constraint/variant_constraint_test.tsv", op="cell",
         where={"gene": "POOLED", "layer": "family",
                "contrast": "P/LP vs B/LB, all layers scorable"},
         column="n_positive", expect="44"),
    dict(id="C134", section="R5",
         claim="and 34 benign ones",
         source="results/constraint/variant_constraint_test.tsv", op="cell",
         where={"gene": "POOLED", "layer": "family",
                "contrast": "P/LP vs B/LB, all layers scorable"},
         column="n_negative", expect="34"),
    dict(id="C135", section="R5",
         claim="FEL finds 5,766 purifying sites across the three paralogues",
         source="results/constraint/fel_status.tsv", op="sum",
         column="n_purifying_q05", expect="5766"),
    dict(id="C136", section="R5",
         claim="and one diversifying site",
         source="results/constraint/fel_status.tsv", op="sum",
         column="n_diversifying_q05", expect="1"),
    dict(id="C137", section="R5",
         claim="AlphaFold covers 20.9 % of UniProt-shaped census records",
         source="results/structures/afdb_coverage_summary.tsv", op="cell",
         where={"scope": "census", "group": "ALL"}, column="usable_fraction",
         expect="0.209", tol=1e-3),
    dict(id="C138", section="R5",
         claim="9 of the 134 representatives have a usable model",
         source="results/structures/afdb_coverage_summary.tsv", op="cell",
         where={"scope": "reps", "group": "ALL"}, column="usable_ge_95pct",
         expect="9"),
    dict(id="C139", section="R5",
         claim="13 of 5,861 full-length census records do (0.2 %)",
         source="results/structures/report.md", op="grep",
         expect="**13** (0.2 %) have a usable model"),
    dict(id="C140", section="R5",
         claim="20 of 20 callable structures agree with the census call",
         source="results/structures/report.md", op="grep",
         expect="(20/20), and no negative control is called at all (0/3)"),
    dict(id="C141", section="R5",
         claim="the IP3-binding core is the best-modelled domain (pLDDT 83.9)",
         source="results/structures/plddt_summary.tsv", op="cell",
         where={"pfam": "PF08709"}, column="median_plddt", expect="83.88",
         tol=0.02),
    dict(id="C142", section="R5",
         claim="the pore the worst (71.0)",
         source="results/structures/plddt_summary.tsv", op="cell",
         where={"pfam": "PF00520"}, column="median_plddt", expect="71.01",
         tol=0.02),
    dict(id="C143", section="R5",
         claim="against 69.5 outside annotated domains",
         source="results/structures/plddt_summary.tsv", op="cell",
         where={"label": "outside annotated domains"}, column="median_plddt",
         expect="69.50", tol=0.02),

    # --------------------------------------------- R6: the annotation
    dict(id="C144", section="R6",
         claim="73.9 % of IP3 receptor loci are complete",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.frac_itpr_complete", expect="0.7393",
         tol=1e-4),
    dict(id="C145", section="R6",
         claim="the ryanodine receptor control is 77.9 %",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.frac_control_complete", expect="0.7792",
         tol=1e-4),
    dict(id="C146", section="R6",
         claim="no overall difference survives BH over all scorable loci",
         source="results/annotation_audit/family_vs_control.tsv", op="cell",
         where={"scope": "all scorable loci",
                "measure": "any annotation failure"}, column="q_bh",
         expect="0.127691", tol=1e-5),
    dict(id="C147", section="R6",
         claim="nor above the contiguity bar",
         source="results/annotation_audit/family_vs_control.tsv", op="cell",
         where={"scope": "loci on a contig that spans the gene (D4)",
                "measure": "any annotation failure"}, column="q_bh",
         expect="0.819481", tol=1e-5),
    dict(id="C148", section="R6",
         claim="42 ITPR loci are held only by a non-coding feature",
         source="results/annotation_audit/family_vs_control.tsv", op="cell",
         where={"scope": "all scorable loci", "measure": "noncoding"},
         column="n_itpr_failing", expect="42"),
    dict(id="C149", section="R6",
         claim="against 16 RyR loci (q = 0.006)",
         source="results/annotation_audit/family_vs_control.tsv", op="cell",
         where={"scope": "all scorable loci", "measure": "noncoding"},
         column="n_ryr_failing", expect="16"),
    dict(id="C150", section="R6",
         claim="but 4 against 5 above the bar (q = 1.0)",
         source="results/annotation_audit/family_vs_control.tsv", op="cell",
         where={"scope": "loci on a contig that spans the gene (D4)",
                "measure": "noncoding"}, column="q_bh", expect="1", tol=1e-6),
    dict(id="C151", section="R6",
         claim="RefSeq annotations are 98.8 % complete",
         source="results/annotation_audit/by_source.tsv", op="cell",
         where={"scope": "all scorable loci", "state": "complete"},
         column="frac_refseq", expect="0.9881", tol=1e-4),
    dict(id="C152", section="R6",
         claim="GenBank annotations 37.5 %",
         source="results/annotation_audit/by_source.tsv", op="cell",
         where={"scope": "all scorable loci", "state": "complete"},
         column="frac_genbank", expect="0.3748", tol=1e-4),
    dict(id="C153", section="R6",
         claim="above the contiguity bar, 99.4 % against 63.8 %",
         source="results/annotation_audit/by_source.tsv", op="cell",
         where={"scope": "loci on a contig that spans the gene (D4)",
                "state": "complete"}, column="frac_genbank", expect="0.6378",
         tol=1e-4),
    dict(id="C154", section="R6",
         claim="the ITPR failure rate falls to 6.7 % above the bar",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.frac_itpr_failure_above_d4",
         expect="0.0669", tol=1e-4),
    dict(id="C155", section="R6",
         claim="the completeness bar sits at the 1.3 % point of 1,077 loci",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.calibration_frac_below_bar",
         expect="0.013", tol=1e-4),
    dict(id="C156", section="R6",
         claim="whose median single-model coverage is 0.993",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.calibration_median", expect="0.993",
         tol=1e-4),
    dict(id="C157", section="R6",
         claim="11,402 full-length family protein records were scored",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_protein_records", expect="11402"),
    dict(id="C158", section="R6",
         claim="4 disagree with the census on family by sequence",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_protein_seq_family_disagrees",
         expect="4"),
    dict(id="C159", section="R6",
         claim="52 of 8,306 vertebrate symbols name the wrong paralogue",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_symbol_wrong_paralog", expect="52"),
    dict(id="C160", section="R6",
         claim="3,872 records carry a placeholder symbol",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_symbol_placeholder", expect="3872"),
    dict(id="C161", section="R6",
         claim="2,395 carry none at all",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_symbol_absent", expect="2395"),
    dict(id="C162", section="R6",
         claim="all 15 zero-hit reference proteomes are gene-caller failures",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_zero_hit_gene_caller", expect="15"),
    dict(id="C163", section="R6",
         claim="the audit produced 297 corrections",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_corrections", expect="297"),
    dict(id="C164", section="R6",
         claim="52 of them high priority",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_corrections_high", expect="52"),
    dict(id="C165", section="R6",
         claim="18 withheld with the reason recorded",
         source="results/annotation_audit/annotation_audit_stats.json",
         op="json", key="headline.n_corrections_vetoed", expect="18"),
    dict(id="C166", section="R6",
         claim="382 loci pass the five eligibility rules",
         source="results/annotation_bugs/case_ranking.tsv", op="count",
         where={"eligible": "True"}, expect="382"),
    dict(id="C167", section="R6",
         claim="the annotation gets 375 of them right (98.2 %)",
         source="results/annotation_bugs/report.md", op="grep",
         expect="at **375** of those (98.2 %) it did"),
    dict(id="C168", section="R6",
         claim="940 of 1,232 demonstrated genes are unreachable by protein search",
         source="results/methods/methods_stats.json", op="json",
         key="headline.gene_recovery.invisible", expect="940"),
    dict(id="C169", section="R6",
         claim="out of 1,232 genes",
         source="results/methods/methods_stats.json", op="json",
         key="headline.gene_recovery.n_genes", expect="1232"),
    dict(id="C170", section="R6",
         claim="386 of them are in species with no reference proteome",
         source="results/methods/methods_stats.json", op="json",
         key="headline.gene_recovery.by_channel.genome_only:no_reference_proteome",
         expect="386"),
    dict(id="C171", section="R6",
         claim="74.3 % for order representatives",
         source="results/methods/methods_stats.json", op="json",
         key="headline.gene_recovery.by_scope.order representative",
         expect="0.7428", tol=1e-4),
    dict(id="C172", section="R6",
         claim="78.5 % for margin species",
         source="results/methods/methods_stats.json", op="json",
         key="headline.gene_recovery.by_scope.margin species",
         expect="0.7855", tol=1e-4),
    dict(id="C173", section="R6",
         claim="67 public RNA-seq runs were quantified",
         source="results/expression/expression_stats.json", op="json",
         key="runs_quantified", expect="67"),
    dict(id="C174", section="R6",
         claim="298 of 314 unmodelled junctions are crossed by reads",
         source="results/expression/report.md", op="grep",
         expect="298 of 314 (94.9 %) junctions no annotated model spans"),
    dict(id="C175", section="R6",
         claim="the cross-mapping control is exactly zero",
         source="results/expression/expression_stats.json", op="json",
         key="crossmap_worst_rate", expect="0.0", tol=1e-9),
]
