"""S14 claims — where the three vertebrate paralogues came from, and what happened to them.

One row per load-bearing number in that part of the manuscript, naming the
committed table it comes from and the operation that recovers it (D12).
Imported and concatenated by `s14_claims.py`, which owns the engine; the
ledger is split across three modules only to keep every file inside the
project's 500-line budget.

  op:   count | cell | nunique | sum | json | grep
  where keys support `col`, `col__startswith`, `col__in` (comma-separated).

`grep` is used where a number is a join or a ratio the other ops cannot
express. It is not a weaker check: the reports it reads are themselves
rendered from the committed tables by script and carry no hand-written
numbers (D13), so a grep row still fails if the data move.
"""

from __future__ import annotations

CLAIMS: list[dict] = [

    # -------------------------------------------------- R3: the origin
    dict(id="C51", section="R3",
         claim="134 representatives were aligned",
         source="results/msa_v2/align_stats.json", op="json",
         key="mafft.n_sequences", expect="134"),
    dict(id="C52", section="R3",
         claim="MAFFT L-INS-i gave 11,777 columns",
         source="results/msa_v2/align_stats.json", op="json",
         key="mafft.columns", expect="11777"),
    dict(id="C53", section="R3",
         claim="trimAl kept 1,797 columns",
         source="results/msa_v2/align_stats.json", op="json",
         key="trimal.columns_kept", expect="1797"),
    dict(id="C54", section="R3",
         claim="96.8 % of kept columns are parsimony-informative",
         source="results/msa_v2/align_stats.json", op="json",
         key="sites.pct_informative", expect="96.8", tol=0.05),
    dict(id="C55", section="R3",
         claim="the ML model is Q.insect+R7",
         source="results/phylogeny/tree_stats.json", op="json",
         key="iqtree.model", expect="Q.insect+R7"),
    dict(id="C56", section="R3",
         claim="the ML log-likelihood is -215,452.0",
         source="results/phylogeny/tree_stats.json", op="json",
         key="iqtree.log_likelihood", expect="-215451.998", tol=0.01),
    dict(id="C57", section="R3",
         claim="69.5 % of internal nodes clear both support thresholds",
         source="results/phylogeny/tree_stats.json", op="json",
         key="analysis.pct_nodes_both_thresholds", expect="69.5", tol=0.05),
    dict(id="C58", section="R3",
         claim="AU rejects ITPR1+ITPR2 at p = 1.8e-05",
         source="results/phylogeny/au_test.tsv", op="cell",
         where={"hypothesis__startswith": "ITPR1 + ITPR2"}, column="p_AU",
         expect="1.8e-05", tol=1e-7),
    dict(id="C59", section="R3",
         claim="AU rejects ITPR1+ITPR3 at p = 1.65e-05",
         source="results/phylogeny/au_test.tsv", op="cell",
         where={"hypothesis__startswith": "ITPR1 + ITPR3"}, column="p_AU",
         expect="1.65e-05", tol=1e-7),
    dict(id="C60", section="R3",
         claim="AU does not reject ITPR2+ITPR3 (p = 0.476)",
         source="results/phylogeny/au_test.tsv", op="cell",
         where={"hypothesis__startswith": "ITPR2 + ITPR3"}, column="p_AU",
         expect="0.476", tol=1e-3),
    dict(id="C61", section="R3",
         claim="AU does not reject the ML tree (p = 0.525)",
         source="results/phylogeny/au_test.tsv", op="cell",
         where={"tree": "ML"}, column="p_AU", expect="0.525", tol=1e-3),
    dict(id="C62", section="R3",
         claim="within-ITPR1 flank Jaccard is 411x its matched null",
         source="results/synteny/pair_stats.tsv", op="cell",
         where={"pair_class": "within_ITPR1", "stratum": "all",
                "key": "relaxed", "window": "fixed10"}, column="ratio",
         expect="410.8862", tol=0.5),
    dict(id="C63", section="R3",
         claim="the ITPR x RyR class sits at the null (mean J 0.0002)",
         source="results/synteny/pair_stats.tsv", op="cell",
         where={"pair_class": "cross_ITPR1_vs_RYR", "stratum": "all",
                "key": "relaxed", "window": "fixed10"}, column="mean_j",
         expect="0.0002", tol=1e-4),
    dict(id="C64", section="R3",
         claim="the flank caller is 405 of 405 correct",
         source="results/synteny/synteny_stats.json", op="json",
         key="caller.n_correct", expect="405"),
    dict(id="C65", section="R3",
         claim="its false-call rate on random windows is 0.008",
         source="results/synteny/synteny_stats.json", op="json",
         key="caller_null.false_call_rate", expect="0.0083", tol=1e-3),
    dict(id="C66", section="R3",
         claim="it places 131 loci the sequence sweep could not",
         source="results/synteny/synteny_stats.json", op="json",
         key="unplaced_supported", expect="131"),
    dict(id="C67", section="R3",
         claim="ITPR1's neighbourhood is paralogous to ITPR2's in 141 genomes",
         source="results/duplication/duplication_stats.json", op="json",
         key="headline.replication.ITPR1_vs_ITPR2.hit", expect="141"),
    dict(id="C68", section="R3",
         claim="out of 175 genomes with both neighbourhoods",
         source="results/duplication/duplication_stats.json", op="json",
         key="headline.replication.ITPR1_vs_ITPR2.n", expect="175"),
    dict(id="C69", section="R3",
         claim="ITPR1 vs ITPR3: 89 of 152",
         source="results/duplication/duplication_stats.json", op="json",
         key="headline.replication.ITPR1_vs_ITPR3.hit", expect="89"),
    dict(id="C70", section="R3",
         claim="ITPR2 vs ITPR3: 4 of 149, exactly the background",
         source="results/duplication/duplication_stats.json", op="json",
         key="headline.replication.ITPR2_vs_ITPR3.hit", expect="4"),
    dict(id="C71", section="R3",
         claim="matched random neighbourhoods carry a link 2.6 % of the time",
         source="results/duplication/duplication_stats.json", op="json",
         key="headline.replication.ITPR1_vs_ITPR2.null_frac",
         expect="0.0258", tol=1e-4),
    dict(id="C72", section="R3",
         claim="ITPR2 vs ITPR3 does not beat that background (p = 0.55)",
         source="results/duplication/duplication_stats.json", op="json",
         key="headline.replication.ITPR2_vs_ITPR3.p", expect="0.5536",
         tol=1e-3),
    dict(id="C73", section="R3",
         claim="teleosts carry a mean of 1.97 ITPR1 copies",
         source="results/duplication/duplication_stats.json", op="json",
         key="headline.teleost_groups.teleost.ITPR1", expect="1.973",
         tol=5e-3),
    dict(id="C74", section="R3",
         claim="97.3 % of teleost genomes carry more than one ITPR1",
         source="results/duplication/duplication_stats.json", op="json",
         key="headline.teleost_groups.teleost.frac_ITPR1_multi",
         expect="0.9726", tol=1e-3),
    dict(id="C75", section="R3",
         claim="the same genomes carry 5.82 ryanodine receptors",
         source="results/duplication/duplication_stats.json", op="json",
         key="headline.teleost_groups.teleost.RYR", expect="5.822", tol=5e-3),
    dict(id="C76", section="R3",
         claim="the two copies are disjoint in 45 of 49 genomes (tetrapod)",
         source="results/duplication/duplication_stats.json", op="json",
         key="headline.dcs.disjoint_tetrapod", expect="45"),
    dict(id="C77", section="R3",
         claim="and 46 of 49 against a pre-3R ray-finned reference",
         source="results/duplication/duplication_stats.json", op="json",
         key="headline.dcs.disjoint_fish", expect="46"),
    dict(id="C78", section="R3",
         claim="all 705 cross-anchor assignments agree",
         source="results/duplication/duplication_stats.json", op="json",
         key="headline.r3.assignments_agreeing", expect="705"),
    dict(id="C79", section="R3",
         claim="20 of 71 two-copy genomes place the copies on different contigs",
         source="results/duplication/duplication_stats.json", op="json",
         key="headline.dispersion.n_different_contigs", expect="20"),
    dict(id="C80", section="R3",
         claim="the ITPR2/ITPR3 split is on the gnathostome stem, 462-563 Ma",
         source="results/reconciliation/duplication_placement.tsv", op="cell",
         where={"topology": "ml", "variant": "with_cyclostome", "rank": "3"},
         column="species_node", expect="Gnathostomata"),
    dict(id="C81", section="R3",
         claim="its younger bracket is 462 Ma",
         source="results/reconciliation/duplication_placement.tsv", op="cell",
         where={"topology": "ml", "variant": "with_cyclostome", "rank": "3"},
         column="age_young_ma", expect="462.0", tol=0.1),
    dict(id="C82", section="R3",
         claim="the ITPR1 split is on the vertebrate stem",
         source="results/reconciliation/duplication_placement.tsv", op="cell",
         where={"topology": "ml", "variant": "with_cyclostome", "rank": "1"},
         column="species_node", expect="Vertebrata"),
    dict(id="C83", section="R3",
         claim="Dollo places the ITPR1 gain node at Vertebrata",
         source="results/loss_counts/loss_counts_stats.json", op="json",
         key="headline.gain_node_itpr1", expect="Vertebrata"),
    dict(id="C84", section="R3",
         claim="and the ITPR2 gain node at Gnathostomata",
         source="results/loss_counts/loss_counts_stats.json", op="json",
         key="headline.gain_node_itpr2", expect="Gnathostomata"),

    # -------------------------------------------------- R4: the fates
    dict(id="C85", section="R4",
         claim="the character matrix holds 927 genome x paralogue cells",
         source="results/loss_dynamics/loss_dynamics_stats.json", op="json",
         key="headline.n_cells", expect="927"),
    dict(id="C86", section="R4",
         claim="none of them reaches the absence state",
         source="results/loss_dynamics/loss_dynamics_stats.json", op="json",
         key="headline.n_absent", expect="0"),
    dict(id="C87", section="R4",
         claim="923 hold a gene that is present",
         source="results/loss_dynamics/loss_dynamics_stats.json", op="json",
         key="headline.n_present", expect="923"),
    dict(id="C88", section="R4",
         claim="43 cells are reassembled across contigs",
         source="results/loss_dynamics/loss_dynamics_stats.json", op="json",
         key="headline.n_fragmented", expect="43"),
    dict(id="C89", section="R4",
         claim="4 cells are paralogue-unassignable",
         source="results/loss_dynamics/loss_dynamics_stats.json", op="json",
         key="headline.n_paralog_unassignable", expect="4"),
    dict(id="C90", section="R4",
         claim="above the bar the minimum is 3.00 gene-equivalents",
         source="results/loss_dynamics/loss_dynamics_stats.json", op="json",
         key="headline.min_implied_above_bar", expect="3.0", tol=1e-6),
    dict(id="C91", section="R4",
         claim="Dollo places zero losses on the family character",
         source="results/loss_counts/loss_counts_stats.json", op="json",
         key="headline.dollo_family_base", expect="0"),
    dict(id="C92", section="R4",
         claim="the family coding manufactures a loss in 2 of 32 settings",
         source="results/loss_counts/loss_counts_stats.json", op="json",
         key="headline.n_settings_family_manufactures", expect="2"),
    dict(id="C93", section="R4",
         claim="the sensitivity grid has 32 settings",
         source="results/loss_counts/loss_counts_stats.json", op="json",
         key="headline.n_settings", expect="32"),
    dict(id="C94", section="R4",
         claim="the paralogue-resolved coding manufactures one in 18 of 32",
         source="results/loss_counts/loss_counts_stats.json", op="json",
         key="headline.n_settings_paralog_manufactures", expect="18"),
    dict(id="C95", section="R4",
         claim="its worst case is 45 loss edges",
         source="results/loss_counts/loss_counts_stats.json", op="json",
         key="headline.max_paralog_losses", expect="45"),
    dict(id="C96", section="R4",
         claim="branch lengths change the count in none of the 32 settings",
         source="results/loss_counts/loss_counts_stats.json", op="json",
         key="headline.branch_length_changes_dollo", expect="0"),
    dict(id="C97", section="R4",
         claim="1,760 loci were scored for frameshift density",
         source="results/loss_counts/loss_counts_stats.json", op="json",
         key="headline.n_scored_loci", expect="1760"),
    dict(id="C98", section="R4",
         claim="44 clear the lesion bar",
         source="results/loss_counts/loss_counts_stats.json", op="json",
         key="headline.n_above_lesion_bar", expect="44"),
    dict(id="C99", section="R4",
         claim="and all 44 are at full coverage",
         source="results/loss_counts/loss_counts_stats.json", op="json",
         key="fossil.n_above_bar_full_coverage", expect="44"),
    dict(id="C100", section="R4",
         claim="one-ratio omega for ITPR1 is 0.0238",
         source="results/selection/omega_table.tsv", op="cell",
         where={"job": "m0_ITPR1"}, column="omega", expect="0.02375",
         tol=1e-5),
    dict(id="C101", section="R4",
         claim="one-ratio omega for ITPR2 is 0.0430",
         source="results/selection/omega_table.tsv", op="cell",
         where={"job": "m0_ITPR2"}, column="omega", expect="0.04303",
         tol=1e-5),
    dict(id="C102", section="R4",
         claim="one-ratio omega for ITPR3 is 0.0415",
         source="results/selection/omega_table.tsv", op="cell",
         where={"job": "m0_ITPR3"}, column="omega", expect="0.04152",
         tol=1e-5),
    dict(id="C103", section="R4",
         claim="on curated CDS only, ITPR1 is 0.0212",
         source="results/selection/omega_table.tsv", op="cell",
         where={"job": "m0_ITPR1_curated"}, column="omega", expect="0.02118",
         tol=1e-5),
    dict(id="C104", section="R4",
         claim="the ITPR1 two-ratio test is significant at q = 2.9e-63",
         source="results/selection/lrt_table.tsv", op="cell",
         where={"test__startswith": "two-ratio (ITPR1"}, column="q_bh",
         expect="2.88318e-63", tol=1e-64),
    dict(id="C105", section="R4",
         claim="RELAX gives k = 9.36, intensified, for ITPR1",
         source="results/selection/relax_table.tsv", op="cell",
         where={"paralog": "ITPR1"}, column="k", expect="9.3587", tol=1e-3),
    dict(id="C106", section="R4",
         claim="k = 0.91, relaxed, for ITPR2",
         source="results/selection/relax_table.tsv", op="cell",
         where={"paralog": "ITPR2"}, column="k", expect="0.9085", tol=1e-3),
    dict(id="C107", section="R4",
         claim="k = 0.84, relaxed, for ITPR3",
         source="results/selection/relax_table.tsv", op="cell",
         where={"paralog": "ITPR3"}, column="k", expect="0.8356", tol=1e-3),
    dict(id="C108", section="R4",
         claim="the ITPR1 stem branch-site omega2 is 5.53",
         source="results/selection/bs_restarts.tsv", op="cell",
         where={"run": "bs_alt_ITPR1_w0.5"}, column="fg_omega2",
         expect="5.52937", tol=1e-4),
    dict(id="C109", section="R4",
         claim="on 11.0 % of sites",
         source="results/selection/bs_restarts.tsv", op="cell",
         where={"run": "bs_alt_ITPR1_w0.5"}, column="prop_fg", expect="0.1102",
         tol=1e-4),
    dict(id="C110", section="R4",
         claim="3 of 12 branch-site restarts fell below their own null",
         source="results/selection/bs_restarts.tsv", op="count",
         where={"below_null": "1"}, expect="3"),
    dict(id="C111", section="R4",
         claim="88.8 % of within-paralogue pairs are past dS = 1.5",
         source="results/methods/methods_stats.json", op="json",
         key="headline.inference.saturation.frac", expect="0.8881", tol=1e-4),
    dict(id="C112", section="R4",
         claim="ITPR3 carries an indel excess against matched siblings, q=0.0032",
         source="results/loss_dynamics/integrity_tests.tsv", op="cell",
         where={"cell": "ITPR3", "matched": "1"}, column="q_bh",
         expect="0.00320932", tol=1e-6),
    dict(id="C113", section="R4",
         claim="ITPR2's excess disappears under identity matching (q = 0.90)",
         source="results/loss_dynamics/integrity_tests.tsv", op="cell",
         where={"cell": "ITPR2", "matched": "1"}, column="q_bh",
         expect="0.902159", tol=1e-4),
    dict(id="C114", section="R4",
         claim="bait identity is the dominant confounder (rho = -0.397)",
         source="results/loss_dynamics/report.md", op="grep",
         expect="-0.397"),
]
