"""S14 driver — assemble the manuscript package.

Stages, in order:

  figures  collect main + Extended Data figures into manuscript/figures/
  claims   re-verify the manuscript's load-bearing numbers against tables
  stitch   concatenate the section files into manuscript/manuscript.md
  pdf      typeset the manuscript with figures embedded (pandoc + xelatex)
  deposit  build the deposit manifest (sizes + SHA-256) and deposit notes

  python scripts/s14_assemble.py                 # all stages
  python scripts/s14_assemble.py --only claims
  python scripts/s14_assemble.py --from stitch
  python scripts/s14_assemble.py --list

The order matters: figures must exist and the numbers must be checked before a
manuscript is stitched, and `deposit` runs last so that the manifest's
checksums describe the files as they finally stand, the typeset PDF
included. A failing claim does not
block the stitch (the draft is still useful) but it does set the exit status,
so a session-end check catches it.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from datetime import date

import s14_claims
import s14_deposit
import s14_figures
import s14_lib as lib
import s14_pdf
import s14_refs

STAGES = ["figures", "claims", "stitch", "pdf", "deposit"]


def _git_revision() -> str:
    try:
        out = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                             cwd=lib.ROOT, capture_output=True, text=True,
                             timeout=10)
        return out.stdout.strip() or "unknown"
    except Exception:                              # noqa: BLE001
        return "unknown"


def stitch() -> int:
    missing = [n for n in lib.SECTION_ORDER if not (lib.MS / n).exists()]
    if missing:
        print(f"  MISSING sections: {', '.join(missing)}", file=sys.stderr)

    parts = [
        "<!-- Generated by scripts/s14_assemble.py — do not edit this file.",
        "     Edit the numbered section files in manuscript/ and re-run. -->",
        "",
        f"*Assembled {date.today().isoformat()} from git {_git_revision()}.*",
        "",
    ]
    for name in lib.SECTION_ORDER:
        path = lib.MS / name
        if not path.exists():
            continue
        parts.append(path.read_text(encoding="utf-8").rstrip())
        parts.append("")
        parts.append("---")
        parts.append("")
    text = "\n".join(parts).rstrip() + "\n"

    # Citations are written in the sections as this project's stable keys and
    # renumbered here, so a section file never carries a number that could
    # drift out of order, and the bibliography is rendered from
    # references.tsv rather than typed (D13).
    status = 1 if missing else 0
    try:
        text, bib, cite_stats = s14_refs.resolve(text)
    except (KeyError, FileNotFoundError) as exc:
        print(f"  CITATIONS: {exc}", file=sys.stderr)
        bib, cite_stats, status = "", {"n_cited": 0}, 1
    if s14_refs.MARKER in text:
        text = text.replace(s14_refs.MARKER, bib)
    elif bib:
        print("  CITATIONS: no {references} marker in the sections; the "
              "bibliography was not placed", file=sys.stderr)
        status = 1

    out = lib.MS / "manuscript.md"
    out.write_text(text, encoding="utf-8")
    words = len(text.split())
    print(f"[s14 stitch] {len(lib.SECTION_ORDER) - len(missing)} sections, "
          f"{words:,} words, {cite_stats['n_cited']} references "
          f"-> manuscript/manuscript.md")
    return status


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--only", choices=STAGES)
    ap.add_argument("--from", dest="from_stage", choices=STAGES)
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    if args.list:
        for s in STAGES:
            print(s)
        return 0

    if args.only:
        todo = [args.only]
    elif args.from_stage:
        todo = STAGES[STAGES.index(args.from_stage):]
    else:
        todo = list(STAGES)

    status = 0
    for stage in todo:
        if stage == "figures":
            status |= s14_figures.run()
        elif stage == "deposit":
            status |= s14_deposit.run()
        elif stage == "claims":
            status |= s14_claims.run(verbose=args.verbose)
        elif stage == "stitch":
            status |= stitch()
        elif stage == "pdf":
            status |= s14_pdf.run()
    return status


if __name__ == "__main__":
    raise SystemExit(main())
