"""S25 stage `stitch` — concatenate the chapters into `thesis/thesis.md`.

The chapter sources place a figure the way `docs/review/` does — a bare image
followed by a caption paragraph that opens with the figure's own reference:

    ![](figures/tree_ml_rooted.png)

    **{fig:tree_ml_rooted}.** The rooted maximum-likelihood phylogram ...

so no chapter file carries a figure number and `{fig:slug}` resolves to
"Figure 6.6" wherever it appears. Citations are the project's stable keys and
are renumbered here in order of first appearance, with the bibliography
rendered from the reference table (D13).

Five things fail the build, over and above the citation and audit checks
`s25_refs.resolve` makes:

* a chapter file missing from `thesis/`;
* a placed figure that the figure map does not declare;
* a declared figure that no chapter places;
* a figure placed in a chapter other than the one it is declared for — a
  chapter may cite its neighbour's result, but it may not print its panel;
* a `{fig:slug}` reference to a figure that is never placed.
"""

from __future__ import annotations

import re
import sys
from datetime import date

import s25_figmap as fm
import s25_figures
import s25_lib as L
import s25_refs

FIG_IMG = re.compile(r"!\[\]\(figures/([A-Za-z0-9_]+)\.png\)")
FIG_REF = re.compile(r"\{fig:([A-Za-z0-9_]+)\}")


def chapter_texts() -> tuple[dict[str, str], list[str]]:
    texts, missing = {}, []
    for name in L.CHAPTER_FILES:
        path = L.TH / name
        if path.exists():
            texts[name] = path.read_text(encoding="utf-8").rstrip()
        else:
            missing.append(name)
    return texts, missing


def run(verbose: bool = False) -> int:
    texts, missing = chapter_texts()
    problems = [f"missing chapter file thesis/{n}" for n in missing]

    nums = s25_figures.numbering()
    declared_chapter = {slug: ch for ch, slug, _s, _c in fm.FIGURES}
    placed: dict[str, str] = {}                       # slug -> chapter file

    for name, text in texts.items():
        for m in FIG_IMG.finditer(text):
            slug = m.group(1)
            if slug not in declared_chapter:
                problems.append(f"thesis/{name} places {slug}, which the "
                                f"figure map does not declare")
                continue
            if slug in placed:
                problems.append(f"{slug} is placed twice: thesis/"
                                f"{placed[slug]} and thesis/{name}")
                continue
            placed[slug] = name
            want = L.FILES_OF_CHAPTER.get(declared_chapter[slug], [])
            if name not in want:
                problems.append(
                    f"thesis/{name} places {slug}, which is declared for "
                    f"chapter {declared_chapter[slug]} "
                    f"({', '.join('thesis/' + w for w in want)})")

    for slug in declared_chapter:
        chapter_written = any(f not in missing for f in
                              L.FILES_OF_CHAPTER.get(declared_chapter[slug], []))
        if slug not in placed and chapter_written:
            problems.append(f"{slug} is declared for chapter "
                            f"{declared_chapter[slug]} but no chapter places "
                            f"it")

    parts = [
        "<!-- Generated by scripts/s25_assemble.py. Do not edit this file.",
        "     Edit the numbered chapter files in thesis/ and re-run. -->",
        "",
        f"*Assembled {date.today().isoformat()}.*",
        "",
    ]
    for name in L.CHAPTER_FILES:
        if name in texts:
            parts += [texts[name], "", "---", ""]
    body = "\n".join(parts).rstrip() + "\n"

    body = FIG_IMG.sub(
        lambda m: f"![](figures/fig_{nums[m.group(1)]}_{m.group(1)}.png)"
        if m.group(1) in nums else m.group(0), body)

    bad_ref: list[str] = []

    def ref_repl(m: re.Match) -> str:
        slug = m.group(1)
        if slug not in placed:
            bad_ref.append(slug)
            return f"Figure ?{slug}?"
        return f"Figure {nums[slug]}"

    body = FIG_REF.sub(ref_repl, body)
    for slug in sorted(set(bad_ref)):
        problems.append(f"{{fig:{slug}}} is referenced but the figure is "
                        f"never placed")

    status = 1 if problems else 0
    try:
        body, bib, stats = s25_refs.resolve(body)
    except (KeyError, FileNotFoundError) as exc:
        print(f"  [FAIL] citations: {exc}", file=sys.stderr)
        bib, stats, status = "", {"n_cited": 0, "n_new": 0}, 1
    if s25_refs.MARKER in body:
        body = body.replace(s25_refs.MARKER, bib)
    elif bib:
        problems.append("no {references} marker in the chapters; the "
                        "bibliography was not placed")
        status = 1

    (L.TH / "thesis.md").write_text(body, encoding="utf-8")
    for p in problems:
        print(f"  [FAIL] {p}", file=sys.stderr)
    words = len(body.split())
    print(f"[s25 stitch] {len(texts)}/{len(L.CHAPTER_FILES)} chapters, "
          f"{words:,} words, {len(placed)} figures placed, "
          f"{stats['n_cited']} references ({stats['n_new']} added for the "
          f"thesis) -> thesis/thesis.md")
    return status


if __name__ == "__main__":
    raise SystemExit(run())
