"""S25 — the load-bearing numbers this thesis states and the paper does not.

The manuscript's ledger covers the numbers both documents make; those are
carried in `s25_claims_carried.py` rather than restated. This module declares
the rest: numbers a longer document has room for, the instrument
measurements the paper compresses into a clause, and the numbers about the
thesis itself — its figures, its references, its controls, its assignment.

Same shape as the manuscript's ledger, plus a `chapter`. Every row's expected
value must appear in that chapter's own text, which is re-checked on every
build (`s25_claims._in_chapter`), so a row here cannot be a check the
document never makes.

  op:   count | cell | nunique | sum | json | grep
"""

from __future__ import annotations

CLAIMS: list[dict] = [
    # ------------------------------------------------- 2. the baseline
    dict(id="T01", chapter=2, section="ch2",
         claim="19 atomic literature claims were audited",
         source="results/s0_baseline/lit_claims.tsv", op="count",
         expect="19"),
    dict(id="T02", chapter=2, section="ch2",
         claim="12 of the 19 were verified as written",
         source="results/s0_baseline/lit_claims.tsv", op="count",
         where={"verdict": "verified"}, expect="12"),
    dict(id="T03", chapter=2, section="ch2",
         claim="2 claims were corrected",
         source="results/s0_baseline/lit_claims.tsv", op="count",
         where={"verdict": "corrected"}, expect="2"),
    dict(id="T04", chapter=2, section="ch2",
         claim="the zebrafish signature query returns 109 protein records",
         source="results/s0_baseline/zebrafish_itpr.tsv", op="count",
         expect="109"),
    dict(id="T05", chapter=2, section="ch2",
         claim="across 10 gene symbols",
         source="results/s0_baseline/zebrafish_itpr.tsv", op="nunique",
         column="gene", expect="10"),
    dict(id="T06", chapter=2, section="ch2",
         claim="ITPR1 has 62 canonical exons",
         source="results/s0_baseline/gene_structure.tsv", op="cell",
         where={"symbol": "ITPR1"}, column="n_exons_canonical", expect="62"),
    dict(id="T07", chapter=2, section="ch2",
         claim="ITPR2 spans 497,888 bp",
         source="results/s0_baseline/gene_structure.tsv", op="cell",
         where={"symbol": "ITPR2"}, column="genomic_span_bp", expect="497888"),
    dict(id="T08", chapter=2, section="ch2",
         claim="ITPR3 spans 76,245 bp",
         source="results/s0_baseline/gene_structure.tsv", op="cell",
         where={"symbol": "ITPR3"}, column="genomic_span_bp", expect="76245"),
    dict(id="T09", chapter=2, section="ch2",
         claim="ITPR1 spans 354,174 bp",
         source="results/s0_baseline/gene_structure.tsv", op="cell",
         where={"symbol": "ITPR1"}, column="genomic_span_bp", expect="354174"),
    dict(id="T10", chapter=2, section="ch2",
         claim="PF08709 is carried by 12,338 proteins",
         source="results/s0_baseline/interpro_signature_counts.tsv", op="cell",
         where={"pfam": "PF08709"}, column="n_proteins", expect="12338"),
    dict(id="T11", chapter=2, section="ch2",
         claim="PF02815 by 23,453",
         source="results/s0_baseline/interpro_signature_counts.tsv", op="cell",
         where={"pfam": "PF02815"}, column="n_proteins", expect="23453"),
    dict(id="T12", chapter=2, section="ch2",
         claim="the generic pore PF00520 by 206,115",
         source="results/s0_baseline/interpro_signature_counts.tsv", op="cell",
         where={"pfam": "PF00520"}, column="n_proteins", expect="206115"),

    # ------------------------------------ 3. two families, one architecture
    dict(id="T13", chapter=3, section="ch3",
         claim="the enumerated space is 15,421 proteins",
         source="results/census_v2/census_v2.tsv", op="count",
         expect="15421"),
    dict(id="T14", chapter=3, section="ch3",
         claim="across 1,488 taxa",
         source="results/census_v2/census_v2.tsv", op="nunique",
         column="taxon_id", expect="1488"),
    dict(id="T15", chapter=3, section="ch3",
         claim="PF08709 advertises 12,339 records",
         source="results/census_v2/interpro_counts.tsv", op="cell",
         where={"pfam_id": "PF08709"}, column="api_count", expect="12339"),
    dict(id="T16", chapter=3, section="ch3",
         claim="and serves 12,507",
         source="results/census_v2/interpro_counts.tsv", op="cell",
         where={"pfam_id": "PF08709"}, column="unique", expect="12507"),
    dict(id="T17", chapter=3, section="ch3",
         claim="PF08454 serves 11,890, 176 fewer than advertised",
         source="results/census_v2/interpro_counts.tsv", op="cell",
         where={"pfam_id": "PF08454"}, column="unique", expect="11890"),
    dict(id="T18", chapter=3, section="ch3",
         claim="2,914 records do not carry PF08709",
         source="results/census_v2/seed_contribution.tsv", op="cell",
         where={"pfam_id": "PF08709", "absent": "2914"}, column="absent",
         expect="2914"),
    dict(id="T19", chapter=3, section="ch3",
         claim="758 of those are called IP3 receptor",
         source="results/census_v2/seed_contribution.tsv", op="cell",
         where={"pfam_id": "PF08709", "absent": "2914"},
         column="absent_called_itpr", expect="758"),
    dict(id="T20", chapter=3, section="ch3",
         claim="across 385 taxa",
         source="results/census_v2/seed_contribution.tsv", op="cell",
         where={"pfam_id": "PF08709", "absent": "2914"}, column="taxa_lost",
         expect="385"),
    dict(id="T21", chapter=3, section="ch3",
         claim="10,256 records carry all three seed signatures",
         source="results/census_v2/seed_contribution.tsv", op="cell",
         where={"pfam_id": "PF01365+PF08454+PF08709"}, column="present",
         expect="10256"),
    dict(id="T22", chapter=3, section="ch3",
         claim="the architecture call gives 6,433 IP3 receptors",
         source="results/census_v2/census_v2.tsv", op="count",
         where={"call": "ITPR"}, expect="6433"),
    dict(id="T23", chapter=3, section="ch3",
         claim="6,807 ryanodine receptors",
         source="results/census_v2/census_v2.tsv", op="count",
         where={"call": "RYR"}, expect="6807"),
    dict(id="T24", chapter=3, section="ch3",
         claim="2,181 records satisfy neither positive test",
         source="results/census_v2/census_v2.tsv", op="count",
         where={"call": "unassigned"}, expect="2181"),
    dict(id="T25", chapter=3, section="ch3",
         claim="the IP3 receptor profile is built from 34 seeds",
         source="results/hmm_sweep/seed_build_stats.json", op="json",
         key="profiles.itpr.n_seeds", expect="34"),
    dict(id="T26", chapter=3, section="ch3",
         claim="the ryanodine profile from 22",
         source="results/hmm_sweep/seed_build_stats.json", op="json",
         key="profiles.ryr.n_seeds", expect="22"),
    dict(id="T27", chapter=3, section="ch3",
         claim="the IP3 receptor profile has 2,684 match states",
         source="results/hmm_sweep/seed_build_stats.json", op="json",
         key="profiles.itpr.match_states", expect="2684"),
    dict(id="T28", chapter=3, section="ch3",
         claim="the union of the two searches is 18,501 targets",
         source="results/census_v3/report.md", op="grep",
         expect="**18,501 targets**"),
    dict(id="T29", chapter=3, section="ch3",
         claim="12,609 hits are declined as module-only matches",
         source="results/census_v3/census_v3_stats.json", op="json",
         key="module_only_declined", expect="12609"),
    dict(id="T30", chapter=3, section="ch3",
         claim="618 sweep hits are absent from the enumeration",
         source="results/census_v3/census_v3_stats.json", op="json",
         key="novel_rows", expect="618"),
    dict(id="T31", chapter=3, section="ch3",
         claim="188 of them are called IP3 receptor",
         source="results/census_v3/census_v3_stats.json", op="json",
         key="novel_calls.ITPR", expect="188"),
    dict(id="T32", chapter=3, section="ch3",
         claim="census v3 holds 16,039 records",
         source="results/census_v3/census_v3_stats.json", op="json",
         key="v3_rows", expect="16039"),
    dict(id="T33", chapter=3, section="ch3",
         claim="8,000 of them are called IP3 receptor",
         source="results/census_v3/census_v3_stats.json", op="json",
         key="calls.ITPR", expect="8000"),
    dict(id="T34", chapter=3, section="ch3",
         claim="7,432 ryanodine receptor",
         source="results/census_v3/census_v3_stats.json", op="json",
         key="calls.RYR", expect="7432"),
    dict(id="T35", chapter=3, section="ch3",
         claim="605 unassigned",
         source="results/census_v3/census_v3_stats.json", op="json",
         key="calls.unassigned", expect="605"),
    dict(id="T36", chapter=3, section="ch3",
         claim="2,787 records the profiles failed to find were looked up",
         source="results/census_v3/census_v3_stats.json", op="json",
         key="missed_by_hmm.total", expect="2787"),
    dict(id="T37", chapter=3, section="ch3",
         claim="none of them was in the database and missed",
         source="results/census_v3/census_v3_stats.json", op="json",
         key="missed_by_hmm.sensitivity_failures", expect="0"),
    dict(id="T38", chapter=3, section="ch3",
         claim="15 of 763 proteomes carry no family record",
         source="results/census_v3/census_v3_stats.json", op="json",
         key="proteomes_without_itpr", expect="15"),

    # ------------------------------------- 6. the alignment and the tree
    dict(id="T39", chapter=6, section="ch6",
         claim="134 representatives were selected",
         source="results/msa_v2/align_stats.json", op="json",
         key="mafft.n_sequences", expect="134"),
    dict(id="T40", chapter=6, section="ch6",
         claim="the alignment is 11,777 columns",
         source="results/msa_v2/align_stats.json", op="json",
         key="mafft.columns", expect="11777"),
    dict(id="T41", chapter=6, section="ch6",
         claim="at 76 % gaps",
         source="results/msa_v2/align_stats.json", op="json",
         key="mafft.gap_pct", expect="76.23"),
    dict(id="T42", chapter=6, section="ch6",
         claim="trimming keeps 1,797 columns",
         source="results/msa_v2/align_stats.json", op="json",
         key="trimal.columns_kept", expect="1797"),
    dict(id="T43", chapter=6, section="ch6",
         claim="15.3 % of them",
         source="results/msa_v2/align_stats.json", op="json",
         key="trimal.pct_kept", expect="15.3", tol=0.01),
    dict(id="T44", chapter=6, section="ch6",
         claim="the representative set is 375,137 residues",
         source="results/msa_v2/report.md", op="grep",
         expect="Total 375,137 residues"),
    dict(id="T45", chapter=6, section="ch6",
         claim="within-paralogue identity is 0.910",
         source="results/msa_v2/report.md", op="grep",
         expect="**0.910**"),
    dict(id="T46", chapter=6, section="ch6",
         claim="identity to the outgroup is 0.253",
         source="results/msa_v2/report.md", op="grep",
         expect="**0.253**"),
    dict(id="T47", chapter=6, section="ch6",
         claim="a separation of 0.656",
         source="results/msa_v2/report.md", op="grep",
         expect="**0.656**"),
    dict(id="T48", chapter=6, section="ch6",
         claim="the tree has 131 internal nodes",
         source="results/phylogeny/report.md", op="grep",
         expect="| internal nodes | 131 |"),
    dict(id="T49", chapter=6, section="ch6",
         claim="91 of them clear both support thresholds",
         source="results/phylogeny/report.md", op="grep",
         expect="| both thresholds | 91 |"),
    dict(id="T50", chapter=6, section="ch6",
         claim="39 tips agree with their census label",
         source="results/phylogeny/membership_audit.tsv", op="count",
         where={"rule": "core"}, expect="39"),
    dict(id="T51", chapter=6, section="ch6",
         claim="no tip is reassigned by the tree",
         source="results/phylogeny/membership_audit.tsv", op="count",
         where={"rule": "reassigned"}, expect="0"),
    dict(id="T52", chapter=6, section="ch6",
         claim="5 tips are left unplaced",
         source="results/phylogeny/membership_audit.tsv", op="count",
         where={"rule": "unconstrained"}, expect="5"),

    # ---------------------------------------------------- 10. selection
    dict(id="T53", chapter=10, section="ch10",
         claim="57 vertebrate tips have a validated coding sequence",
         source="results/selection/cds_status.tsv", op="count",
         expect="57"),
    dict(id="T54", chapter=10, section="ch10",
         claim="the trimmed codon alignment is 2,459 codons",
         source="results/selection/report.md", op="grep",
         expect="**2459 codons**"),
    dict(id="T56", chapter=10, section="ch10",
         claim="12 likelihood-ratio tests were corrected together",
         source="results/selection/selection_stats.json", op="json",
         key="n_lrt", expect="12"),

    # ------------------------------------------------- 12. the ligand site
    dict(id="T57", chapter=12, section="ch12",
         claim="the shells are measured in 6 independent depositions",
         source="results/ligand_site/shell_agreement.tsv", op="nunique",
         column="pdb_id", expect="6"),
    dict(id="T58", chapter=12, section="ch12",
         claim="486 non-vertebrate records resolve both modules",
         source="results/ligand_site/deep_lineage_panel.tsv", op="count",
         where={"in_test": "True"}, expect="486"),

    # --------------------------------------------------- 14. the methods
    dict(id="T59", chapter=14, section="ch14",
         claim="437 constructed negative controls are declared",
         source="thesis/control_inventory.tsv", op="sum",
         column="n_controls", expect="437"),
    dict(id="T60", chapter=14, section="ch14",
         claim="across 19 test modules",
         source="thesis/control_inventory.tsv", op="count", expect="19"),
    dict(id="T61", chapter=14, section="ch14",
         claim="76 references were added for the thesis",
         source="thesis/reference_audit.tsv", op="count", expect="76"),
    dict(id="T62", chapter=14, section="ch14",
         claim="all 76 are verified against a live record",
         source="thesis/reference_audit.tsv", op="count",
         where={"verdict": "verified"}, expect="76"),
    dict(id="T63", chapter=14, section="ch14",
         claim="26 figure-audit findings were recorded",
         source="results/supplementary/figure_findings.tsv", op="count",
         expect="26"),
    dict(id="T64", chapter=14, section="ch14",
         claim="16 of them were fixed in the legend",
         source="results/supplementary/figure_findings.tsv", op="count",
         where={"status": "fixed_legend"}, expect="16"),
    dict(id="T65", chapter=14, section="ch14",
         claim="10 in the figure",
         source="results/supplementary/figure_findings.tsv", op="count",
         where={"status": "fixed_figure"}, expect="10"),
    dict(id="T66", chapter=14, section="ch14",
         claim="the manuscript ledger carries 276 declarations",
         source="manuscript/claims_check.tsv", op="count", expect="276"),

    # ---------------------------------------------- appendices (ch 14/15)
    dict(id="T68", chapter=14, section="appendix-E",
         claim="18 build guards are broken on purpose and all fire",
         source="thesis/guard_check.tsv", op="count",
         where={"verdict": "fired"}, expect="18"),
    dict(id="T69", chapter=14, section="appendix-E",
         claim="the thesis places 103 figures",
         source="thesis/figure_manifest.tsv", op="count", expect="103"),
    dict(id="T70", chapter=14, section="appendix-E",
         claim="37 results directories are assigned to a chapter",
         source="thesis/chapter_assignment.tsv", op="count",
         where={"rule__startswith": "T"}, expect="37"),
    dict(id="T83", chapter=14, section="ch14",
         claim="87 decisions are recorded, as chapter 14 also states",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "decisions_recorded"}, column="value", expect="87"),
    dict(id="T84", chapter=14, section="ch14",
         claim="across 35 logged sessions, as chapter 14 also states",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "sessions_logged"}, column="value", expect="35"),

    # -------------------------------- 16. how the project was carried out
    # Measured from the repository by `s25_production.py` on every build, so
    # a number here moves when the project does and the ledger says so.
    dict(id="T71", chapter=16, section="ch16",
         claim="35 sessions are logged",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "sessions_logged"}, column="value", expect="35"),
    dict(id="T72", chapter=16, section="ch16",
         claim="they ran across 9 working days",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "session_days"}, column="value", expect="9"),
    dict(id="T73", chapter=16, section="ch16",
         claim="the ledger holds 36 tasks",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "ledger_tasks"}, column="value", expect="36"),
    dict(id="T74", chapter=16, section="ch16",
         claim="34 of them are complete",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "ledger_completed"}, column="value", expect="34"),
    dict(id="T75", chapter=16, section="ch16",
         claim="87 methodological decisions are recorded",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "decisions_recorded"}, column="value", expect="87"),
    dict(id="T76", chapter=16, section="ch16",
         claim="373 analysis scripts were written",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "analysis_scripts"}, column="value", expect="373"),
    dict(id="T77", chapter=16, section="ch16",
         claim="the search application is 9,243 lines",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "application_lines"}, column="value",
         expect="9243"),
    dict(id="T78", chapter=16, section="ch16",
         claim="444 result tables are committed",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "committed_result_tables"}, column="value",
         expect="444"),
    dict(id="T79", chapter=16, section="ch16",
         claim="111 figures are committed",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "committed_figures"}, column="value", expect="111"),
    dict(id="T80", chapter=16, section="ch16",
         claim="28 task reports are rendered",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "task_reports"}, column="value", expect="28"),
    dict(id="T81", chapter=16, section="ch16",
         claim="those reports run to 109,250 words",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "task_report_words"}, column="value",
         expect="109250"),
    dict(id="T82", chapter=16, section="ch16",
         claim="the first session ran on 2026-08-18",
         source="thesis/production_stats.tsv", op="cell",
         where={"metric": "first_session"}, column="value",
         expect="2026-08-18"),

    dict(id="T67", chapter=14, section="appendix-B",
         claim="the control inventory is derived from 19 modules",
         source="thesis/control_inventory.tsv", op="nunique",
         column="module", expect="19"),
]
