"""S26 stage `readme`: render `papers/README.md` from the series' own tables.

Brief step 5: what each paper claims, what it does not, and which committed
tables it stands on. Everything but the "does not claim" lines is read from
committed files: each paper's title, question and standalone answer from its
configuration; its primary results from `paper_assignment.tsv`; its claim
count from `claims_check.tsv`; its citations from `dependency_graph.tsv`;
its pages and words from the build. Those lines are hand-written because a
limit is a judgement, and each one is taken from the paper's own discussion,
so the README cannot state a limit the paper does not.
"""

from __future__ import annotations

import sys

import s26_lib as L
import s26_pdf

#: What each paper does not claim, from its own discussion.
NOT_CLAIMED = {
    "range": [
        "that lineages without the receptor lack IP₃-evoked calcium release; "
        "what replaces it there is not measured",
        "that the labelled-bait margin reaches every deep lineage: it cannot "
        "reach the characterised *Dictyostelium* receptor, which the profile "
        "seed set carries for that reason",
    ],
    "origin": [
        "which of the two early genome duplications made which split; the "
        "dated placements separate the splits, not the rounds",
        "anything about losses or about what the paralogues do",
    ],
    "retention": [
        "why the paralogues are retained: non-redundant function and dosage "
        "balance both fit, and the analysis cannot tell them apart",
        "the paralogue identity of the four cyclostome cells, which stay "
        "unassignable",
    ],
    "archive": [
        "that any single annotation is wrong beyond the two cases proved at "
        "the exon; the 297 corrections are proposals for curators",
        "a failure rate for genes the sweep itself missed, which cannot "
        "appear as annotation failures",
    ],
    "constraint": [
        "a pathogenicity call for any variant; the per-residue tables "
        "stratify uncertain variants and do not classify them",
        "that the deep orthologue layer is the best classifier: it ranks "
        "third of four",
    ],
    "ligand": [
        "that the ligand site is unconstrained; it is not more constrained "
        "than the pore, and which way the contrast falls depends on where "
        "the pore is taken to end",
        "that ligand binding and fold can be separated by sequence alone",
    ],
}


def _count(path, **where) -> int:
    if not path.exists():
        return 0
    return sum(1 for r in L.read_tsv(path)
               if all(r.get(k) == v for k, v in where.items()))


def render() -> str:
    assign = L.read_tsv(L.PAPERS / "paper_assignment.tsv")
    graph = L.read_tsv(L.PAPERS / "dependency_graph.tsv")
    claims = L.read_tsv(L.PAPERS / "claims_check.tsv")
    n_shared = sum(1 for c in claims if "," in c["section"])
    lines = [
        "# The paper series",
        "",
        "<!-- Generated by scripts/s26_readme.py from the series' committed "
        "tables. Do not edit. -->",
        "",
        f"The project's results are reported as {len(L.SERIES)} papers, "
        "each answering one question with its own controls, its own "
        "declared scope and its own figures. The single manuscript "
        "(`manuscript/`) and the thesis (`thesis/`) report the same work in "
        "one document each. The rules the grouping was derived from are in "
        "[`paper_rules.md`](paper_rules.md), committed before the "
        "assignment. The assignment itself, one row per results entry with "
        "the rule that placed it, is in "
        "[`paper_assignment.tsv`](paper_assignment.tsv).",
        "",
        f"One claims ledger covers the series: {len(claims)} load-bearing "
        f"numbers, {n_shared} of them stated in more than one paper and "
        "checked once ([`claims_check.tsv`](claims_check.tsv)). "
        "`python scripts/s26_assemble.py` rebuilds every paper from the "
        "committed tables and exits non-zero if any guard fails; every "
        "guard is also broken on purpose on each build "
        "([`guard_check.tsv`](guard_check.tsv)).",
        "",
        "| # | Paper | Question | Pages | Claims | Cites |",
        "|---|---|---|---|---|---|",
    ]
    for pid in L.SERIES:
        cfg = L.paper(pid)
        n_claims = sum(1 for c in claims if pid in c["section"].split(","))
        cites = sorted((r["cited"] for r in graph if r["citing"] == pid),
                       key=L.number)
        pdf = s26_pdf.pdf_path(pid)
        pages = s26_pdf.page_count(pdf) if pdf.exists() else "?"
        lines.append(
            f"| {L.number(pid)} | [{cfg.TITLE}]({pid}/{pdf.name}) | "
            f"{cfg.QUESTION} | {pages} | {n_claims} | "
            f"{', '.join(str(L.number(c)) for c in cites) or 'none'} |")
    lines += ["", "Submission order is the table's order. A paper cites only "
              "papers above it, which the build checks, so each can be read "
              "when it appears.", ""]
    for pid in L.SERIES:
        cfg = L.paper(pid)
        mine = [r for r in assign if r["paper"] == pid]
        entries = []
        for r in mine:
            e = r["results_entry"]
            entries.append(f"`{e}`" if r["files"] == "*"
                           else f"`{e}/{r['files']}`")
        lines += [
            f"## {L.number(pid)}. {cfg.TITLE}",
            "",
            f"**Question.** {cfg.QUESTION}",
            "",
            f"**What it claims on its own (P6).** "
            f"{' '.join(cfg.STANDALONE.split())}",
            "",
            "**What it does not claim.**",
            "",
            *[f"- {x}." for x in NOT_CLAIMED[pid]],
            "",
            f"**The controls it measures itself (P2).** "
            + "; ".join(f"{w} (`{p}`)" for w, p in cfg.CONTROLS) + ".",
            "",
            f"**The committed results it is primary in (P5).** "
            + ", ".join(entries) + ".",
            "",
            f"Source: [`{pid}/`]({pid}/); built paper: `{pid}/paper.md` and "
            f"`{pid}/{s26_pdf.pdf_path(pid).name}`.",
            "",
        ]
    return "\n".join(lines)


def run() -> int:
    missing = [p for p in L.SERIES if not NOT_CLAIMED.get(p)]
    for p in missing:
        print(f"  [FAIL] {p}: no 'does not claim' lines", file=sys.stderr)
    (L.PAPERS / "README.md").write_text(render(), encoding="utf-8")
    print(f"[s26 readme] papers/README.md for {len(L.SERIES)} papers: "
          f"{len(missing)} failure(s)")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(run())
