"""S26 ledger: the load-bearing numbers of the origin paper.

`CARRY` names claims already declared by the manuscript's ledger (`C…`), the
thesis's (`T…`) or another paper, by identifier; `CLAIMS` declares numbers no
earlier ledger has, with the `OR` prefix `s26_claims.PREFIX` gives this paper.
Every value must appear in the paper's own text.

Three kinds of number are declared here rather than carried. Values the
upstream ledgers record at a precision or in a form the text cannot state
(`410.8862` for "411-fold", `147445.0` for "147,445 bp") are re-declared at
the precision the text states, with a tolerance that admits the table's own
value. Percentages the tables store as fractions are checked with `grep`
against the report rendered from the same table, since the appearance rule
cannot rescale. And the p-values the text writes in scientific notation are
not declared at all; the log-likelihood costs beside them are.
"""

_SYN = "results/synteny/synteny_stats.json"
_PAIR = "results/synteny/pair_stats.tsv"
_DUP = "results/duplication/duplication_stats.json"
_ARCH = "results/gene_architecture/gene_architecture_stats.json"
_REC = "results/reconciliation"
_BASE = dict(stratum="all", key="relaxed", window="fixed10")

CARRY: list[str] = [
    # scope and tree
    "C277", "C278", "C279", "C280", "C281", "C282", "C283", "C284", "C285", "C286", "C287",
    "C07", "C51", "C52", "C53", "C54", "C55", "C57", "C60", "C61",
    "T41", "T43", "T45", "T46", "T48", "T49", "T50", "T51", "T52",
    # neighbourhoods and paralogy
    "C63", "C64", "C66", "C67", "C68", "C69", "C70", "C73", "C75",
    "C76", "C77", "C78", "C79",
    # dating
    "C80", "C81", "C82",
    # gene architecture
    "C181", "C182", "C183", "C186", "C187", "C188", "C190",
    "C193", "C194", "C195", "C199", "C202", "C204", "C205", "C206",
    "C207", "C208", "C209", "C210", "C214", "C215", "C216", "C217",
    "C218", "C219", "C220", "C221", "C260", "C263", "C264", "C265",
    "C268",
]

CLAIMS: list[dict] = [
    # ------------------------------------------------------------ scope
    dict(id="OR01", claim="the neighbourhood analysis covers 2,144 loci",
         source=_SYN, op="json", key="n_loci", expect="2144"),
    dict(id="OR02", claim="274 assemblies carry a gene annotation to read",
         source=_SYN, op="json", key="n_genomes_with_gene_table",
         expect="274"),
    dict(id="OR03", claim="the replication runs over 309 vertebrate genomes",
         source=_DUP, op="json", key="headline.n_genomes", expect="309"),
    dict(id="OR04", claim="the species tree has 29 named internal nodes",
         source=f"{_REC}/species_tree_calibrations.tsv", op="count",
         expect="29"),
    dict(id="OR05", claim="the reconciliation maps 57 vertebrate tips",
         source=f"{_REC}/reconciliation_summary.tsv", op="cell",
         where=dict(topology="ml", variant="with_cyclostome"),
         column="n_tips", expect="57"),
    # ------------------------------------------------------------ tree
    dict(id="OR06", claim="ITPR1+ITPR2 costs 114.02 log-likelihood units",
         source="results/phylogeny/au_test.tsv", op="cell",
         where=dict(tree="H1_12"), column="deltaL", expect="114.02"),
    dict(id="OR07", claim="ITPR1+ITPR3 costs 113.98 log-likelihood units",
         source="results/phylogeny/au_test.tsv", op="cell",
         where=dict(tree="H2_13"), column="deltaL", expect="113.98"),
    dict(id="OR08", claim="the AU 95 % confidence set holds 2 topologies",
         source="results/methods/inference_summary.json", op="json",
         key="tree_confidence_set", expect="2"),
    dict(id="OR09", claim="nine claim clades are held under --bnni",
         source="results/phylogeny/bnni_comparison.tsv", op="count",
         where=dict(verdict="held"), expect="9"),
    # ------------------------------------------------------ neighbourhoods
    dict(id="OR10", claim="within-ITPR1 similarity is 411-fold its null",
         source=_PAIR, op="cell", where=dict(_BASE, pair_class="within_ITPR1"),
         column="ratio", expect="411", tol=0.5),
    dict(id="OR11", claim="within-ITPR3 similarity is 216-fold its null",
         source=_PAIR, op="cell", where=dict(_BASE, pair_class="within_ITPR3"),
         column="ratio", expect="216", tol=0.5),
    dict(id="OR12", claim="168,241 pairs of ITPR and RyR loci were compared",
         source=_PAIR, op="sum", column="n_pairs",
         where=dict(_BASE, pair_class__in=(
             "cross_ITPR1_vs_RYR,cross_ITPR2_vs_RYR,cross_ITPR3_vs_RYR")),
         expect="168241"),
    dict(id="OR13", claim="the caller was calibrated on 503 confirmed loci",
         source=_SYN, op="json", key="caller.n", expect="503"),
    dict(id="OR14", claim="726 random windows were offered to the caller",
         source=_SYN, op="json", key="caller_null.n", expect="726"),
    dict(id="OR15", claim="the caller called 6 of them",
         source=_SYN, op="json", key="caller_null.n_called", expect="6"),
    dict(id="OR16", claim="932 matched random neighbourhoods form the null",
         source=_DUP, op="json", key="headline.replication_null.pairs",
         expect="932"),
    dict(id="OR17", claim="ITPR1 vs ITPR2 links in 80.6 % of genomes",
         source="results/duplication/report.md", op="grep",
         expect="141 (80.6%)"),
    dict(id="OR18", claim="ITPR1 vs ITPR3 links in 58.6 % of genomes",
         source="results/duplication/report.md", op="grep",
         expect="89 (58.6%)"),
    dict(id="OR19", claim="the random-window link rate is 2.6 %",
         source="results/duplication/report.md", op="grep",
         expect="2.7% against a 2.6% background"),
    dict(id="OR20", claim="ITPR1 vs ITPR2 replicates in ten classes",
         source=_DUP, op="json",
         key="headline.replication.ITPR1_vs_ITPR2.classes", expect="10"),
    dict(id="OR21", claim="ITPR1 vs ITPR3 replicates in nine classes",
         source=_DUP, op="json",
         key="headline.replication.ITPR1_vs_ITPR3.classes", expect="9"),
    dict(id="OR22", claim="ITPR2 vs ITPR3 does not beat background, p 0.554",
         source=_DUP, op="json", key="headline.replication.ITPR2_vs_ITPR3.p",
         expect="0.554", tol=0.0005),
    dict(id="OR23", claim="the vertebrate-dated GRM link is in 84 genomes",
         source=_DUP, op="json",
         key="headline.replication.ITPR1_vs_ITPR3.hit_2R", expect="84"),
    dict(id="OR24", claim="the BHLHE link is vertebrate-dated in 2 genomes",
         source=_DUP, op="json",
         key="headline.replication.ITPR1_vs_ITPR2.hit_2R", expect="2"),
    # ------------------------------------------------------------ dating
    dict(id="OR25", claim="crown Vertebrata estimates run from 480 Ma",
         source=f"{_REC}/species_tree_calibrations.tsv", op="cell",
         where=dict(node="Vertebrata"), column="age_lo", expect="480"),
    dict(id="OR26", claim="to 615 Ma",
         source=f"{_REC}/species_tree_calibrations.tsv", op="cell",
         where=dict(node="Vertebrata"), column="age_hi", expect="615"),
    dict(id="OR27", claim="around a point age of 563 Ma",
         source=f"{_REC}/species_tree_calibrations.tsv", op="cell",
         where=dict(node="Vertebrata"), column="age_ma", expect="563"),
    dict(id="OR28", claim="all 5 topologies place the deepest dup at "
         "Vertebrata with the cyclostome loci kept",
         source=f"{_REC}/reconciliation_summary.tsv", op="count",
         where=dict(variant="with_cyclostome",
                    deepest_paralog_dup_node="Vertebrata"), expect="5"),
    dict(id="OR29", claim="the weakest vertebrate-subtree node is 17.4/54",
         source=f"{_REC}/duplication_placement.tsv", op="cell",
         where=dict(topology="ml", variant="with_cyclostome", rank="2"),
         column="gene_node_support", expect="17.4/54"),
    dict(id="OR30", claim="the subtree has 112 edges to re-root at",
         source=f"{_REC}/report.md", op="grep",
         expect="all **112 of its edges**"),
    dict(id="OR31", claim="the minimum-event rooting needs 64 events",
         source=f"{_REC}/rooting_check.tsv", op="cell",
         where=dict(is_minimum="minimum"), column="total_events",
         expect="64"),
    dict(id="OR32", claim="the outgroup rooting needs 67 events",
         source=f"{_REC}/rooting_check.tsv", op="cell",
         where=dict(edge_index="-1"), column="total_events", expect="67"),
    dict(id="OR33", claim="the shortest cyclostome tip is 0.957 of median",
         source=f"{_REC}/branch_lengths.tsv", op="cell",
         where=dict(label="vertebrate_basal_Petromyzon_marinus_Sea_lamprey_"
                    "A0AAJ7U4X1"), column="vs_median", expect="0.957"),
    dict(id="OR34", claim="the longest cyclostome tip is 1.045 of median",
         source=f"{_REC}/branch_lengths.tsv", op="cell",
         where=dict(label="vertebrate_basal_Myxine_glutinosa_GCF_964187855.1"
                    "_ITPR1_86116883"), column="vs_median", expect="1.045"),
    dict(id="OR35", claim="six cyclostome loci are in the tree",
         source=f"{_REC}/cyclostome_loci.tsv", op="count", expect="6"),
    dict(id="OR36", claim="the reconciliation implies 47 lost cells",
         source="results/methods/inference_summary.json", op="json",
         key="reconciliation.implied", expect="47"),
    dict(id="OR37", claim="26 of them are sampling artefacts",
         source="results/methods/inference_summary.json", op="json",
         key="reconciliation.artefact", expect="26"),
    dict(id="OR38", claim="0 are corroborated",
         source="results/methods/inference_summary.json", op="json",
         key="reconciliation.corroborated", expect="0"),
    # ------------------------------------------------------------ teleosts
    dict(id="OR39", claim="73 teleost genomes are above the bar",
         source=_DUP, op="json", key="headline.teleost_groups.teleost.n",
         expect="73"),
    dict(id="OR40", claim="teleosts carry 1.041 ITPR2",
         source=_DUP, op="json", key="headline.teleost_groups.teleost.ITPR2",
         expect="1.041"),
    dict(id="OR41", claim="teleosts carry 1.041 ITPR3",
         source=_DUP, op="json", key="headline.teleost_groups.teleost.ITPR3",
         expect="1.041"),
    dict(id="OR42", claim="97.3 % of teleosts carry two ITPR1",
         source="results/duplication/report.md", op="grep",
         expect="| 5.82 | 97.3% |"),
    dict(id="OR43", claim="four pre-3R ray-finned genomes",
         source=_DUP, op="json",
         key="headline.teleost_groups.pre_3R_outgroup.n", expect="4"),
    dict(id="OR44", claim="71 teleost genomes carry two ITPR1 copies",
         source=_DUP, op="json", key="headline.dispersion.n_two_copy_genomes",
         expect="71"),
    dict(id="OR45", claim="same-contig copies sit a median 8,870,578 bp apart",
         source=_DUP, op="json",
         key="headline.dispersion.median_gap_bp_same_contig",
         expect="8870578"),
    dict(id="OR46", claim="the closest pair is 535,374 bp apart",
         source=_DUP, op="json", key="headline.dispersion.min_gap_bp",
         expect="535374"),
    dict(id="OR47", claim="49 two-copy genomes have both copies flanked",
         source=_DUP, op="json", key="headline.dcs.n_pairs", expect="49"),
    dict(id="OR48", claim="anchors come from 6 orders",
         source=_DUP, op="json", key="headline.r3.anchors", expect="6"),
    dict(id="OR49", claim="bait and block agree six times of six",
         source=_DUP, op="json", key="headline.r3.bait_concordance_agree",
         expect="6"),
    # ----------------------------------------------------- architecture
    dict(id="OR50", claim="99.89 % of junctions are spliceable",
         source="results/gene_architecture/report.md", op="grep",
         expect="**99.89 %**"),
    dict(id="OR52", claim="ITPR1 carries 8,250 bp of coding sequence",
         source=_ARCH, op="json", key="headline.by_paralog.ITPR1.cds_bp",
         expect="8250", tol=0.5),
    dict(id="OR53", claim="ITPR2 carries 8,100 bp",
         source=_ARCH, op="json", key="headline.by_paralog.ITPR2.cds_bp",
         expect="8100", tol=0.5),
    dict(id="OR54", claim="ITPR3 carries 8,008 bp",
         source=_ARCH, op="json", key="headline.by_paralog.ITPR3.cds_bp",
         expect="8008", tol=0.5),
    dict(id="OR55", claim="ITPR1 mean exon length 141.4 bp",
         source=_ARCH, op="json",
         key="headline.by_paralog.ITPR1.mean_exon_bp", expect="141.4"),
    dict(id="OR56", claim="ITPR2 mean exon length 142.2 bp",
         source=_ARCH, op="json",
         key="headline.by_paralog.ITPR2.mean_exon_bp", expect="142.2"),
    dict(id="OR57", claim="ITPR3 mean exon length 137.8 bp",
         source=_ARCH, op="json",
         key="headline.by_paralog.ITPR3.mean_exon_bp", expect="137.8"),
    dict(id="OR58", claim="ITPR1 spans a median 147,445 bp",
         source=_ARCH, op="json", key="headline.by_paralog.ITPR1.span_bp",
         expect="147445", tol=0.5),
    dict(id="OR59", claim="ITPR2 spans 243,700 bp",
         source=_ARCH, op="json", key="headline.by_paralog.ITPR2.span_bp",
         expect="243700", tol=0.5),
    dict(id="OR60", claim="ITPR3 spans 58,175 bp",
         source=_ARCH, op="json", key="headline.by_paralog.ITPR3.span_bp",
         expect="58175", tol=0.5),
    dict(id="OR61", claim="the RyR control carries 14,910 bp",
         source=_ARCH, op="json", key="headline.by_paralog.RYR.cds_bp",
         expect="14910", tol=0.5),
    dict(id="OR62", claim="all 14 anchor residues land in one column",
         source="results/gene_architecture/frame_anchors.tsv", op="count",
         where=dict(one_column="1"), expect="14"),
    dict(id="OR63", claim="ITPR1 vs ITPR2 shared introns 87.6-fold",
         source=_ARCH, op="json",
         key="headline.shared.ITPR1|ITPR2.enrichment", expect="87.6",
         tol=0.05),
    dict(id="OR64", claim="ITPR1 vs ITPR3 85.6-fold",
         source=_ARCH, op="json",
         key="headline.shared.ITPR1|ITPR3.enrichment", expect="85.6",
         tol=0.05),
    dict(id="OR65", claim="ITPR2 vs ITPR3 88.4-fold",
         source=_ARCH, op="json",
         key="headline.shared.ITPR2|ITPR3.enrichment", expect="88.4",
         tol=0.05),
    dict(id="OR66", claim="the RyR core holds 91 positions at 90 %",
         source=_ARCH, op="json", key="headline.conservation.RYR.at_90pc",
         expect="91"),
    dict(id="OR67", claim="406 termini fall inside an exon",
         source=_ARCH, op="json", key="headline.fragments.termini_mid_exon",
         expect="406"),
    dict(id="OR68", claim="353 termini fall inside an intron",
         source=_ARCH, op="json",
         key="headline.fragments.termini_in_intron", expect="353"),
    dict(id="OR69", claim="the tandem detector finds 342 duplicated cells",
         source=_ARCH, op="json", key="headline.tandem_control.tp",
         expect="342"),
    dict(id="OR70", claim="and wrongly calls 21 single-copy ones",
         source=_ARCH, op="json", key="headline.tandem_control.fp",
         expect="21"),
]
