"""S26 stage `stitch`: one paper's section files -> `papers/<id>/paper.md`.

Resolves the three kinds of stable reference a paper's source is written in,
so none of them is ever a number typed by hand:

* `{fig:<slug>}` -> `Fig. N` / `Extended Data Fig. N` / `Supplementary
  Fig. N`, numbered by `s26_figures.numbering` (first mention in the body);
* `{paper:<id>}` -> `companion paper N`, with the companion list rendered
  into `{companions}` from the series declaration;
* `[R22]` -> a number, with the bibliography rendered into `{references}`
  from `results/s0_baseline/references.tsv` by `s14_refs.resolve`, the
  manuscript's own resolver. A cited key with no reference row fails.

Fails on a missing section, a reference to an unknown paper, a paper citing
itself, and any marker left unresolved.
"""

from __future__ import annotations

import re
import subprocess
import sys
from datetime import date

import s14_refs
import s26_figures
import s26_lib as L

COMPANIONS = "{companions}"


def _git_revision() -> str:
    try:
        out = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                             cwd=L.ROOT, capture_output=True, text=True,
                             timeout=10)
        return out.stdout.strip() or "unknown"
    except Exception:                                   # noqa: BLE001
        return "unknown"


def order_legends(pid: str, text: str) -> str:
    """Legend paragraphs sorted into the order the figures are numbered in.

    Numbering follows first mention in the body, so a legend section written
    in any other order prints Extended Data Fig. 2 before Extended Data
    Fig. 1, which the first page read of the series found in four papers.
    Paragraphs that are not legends (the heading, a note) keep their place
    ahead of the first legend.
    """
    nums = s26_figures.numbering(pid)
    kinds = list(L.KINDS)
    paras = text.split("\n\n")
    lead, legends = [], []
    for para in paras:
        m = L.LEGEND_HEAD.match(para.strip())
        if m and m.group(1) in nums:
            kind, n = nums[m.group(1)]
            legends.append(((kinds.index(kind), n), para))
        elif legends:
            legends[-1] = (legends[-1][0], legends[-1][1] + "\n\n" + para)
        else:
            lead.append(para)
    return "\n\n".join(lead + [p for _k, p in sorted(legends,
                                                      key=lambda x: x[0])])


def resolve_figures(pid: str, text: str) -> str:
    nums = s26_figures.numbering(pid)

    def repl(m: re.Match) -> str:
        slug = m.group(1)
        if slug not in nums:
            return m.group(0)
        kind, n = nums[slug]
        return f"{L.KINDS[kind]} {n}"
    return L.FIG_REF.sub(repl, text)


def resolve_papers(pid: str, text: str) -> tuple[str, list[str], list[str]]:
    """Returns (text, cited paper ids in order, failures)."""
    fails, cited = [], []

    def repl(m: re.Match) -> str:
        other = m.group(1)
        if other not in L.SERIES:
            fails.append(f"{pid}: {{paper:{other}}} names no paper")
            return m.group(0)
        if other == pid:
            fails.append(f"{pid}: a paper cites itself")
        if other not in cited:
            cited.append(other)
        return f"companion paper {L.number(other)}"
    text = L.PAPER_REF.sub(repl, text)
    return text, cited, fails


def companion_list(cited: list[str]) -> str:
    if not cited:
        return "This paper cites no other paper in the series."
    lines = []
    for other in sorted(cited, key=L.number):
        cfg = L.paper(other)
        lines.append(f"{L.number(other)}. {L.AUTHOR}. {cfg.TITLE}. "
                     f"*In preparation* (paper {L.number(other)} of "
                     f"{len(L.SERIES)} in this series; source in "
                     f"`papers/{other}/`).")
    return "\n\n".join(lines)


def render(pid: str) -> tuple[str, list[str], dict]:
    """The stitched paper, its failures and statistics."""
    fails = []
    missing = [n for n in L.SECTIONS if not (L.paper_dir(pid) / n).exists()]
    for n in missing:
        fails.append(f"{pid}: missing section {n}")
    parts = [
        f"<!-- Generated by scripts/s26_assemble.py -- do not edit. Edit the "
        f"section files in papers/{pid}/ and re-run. -->",
        "",
        f"*Assembled {date.today().isoformat()} from git "
        f"{_git_revision()}.*",
        "",
    ]
    for name in L.SECTIONS:
        body = L.section_text(pid, name).rstrip()
        if name in L.LEGEND_SECTIONS:
            body = order_legends(pid, body)
        if body:
            parts += [body, ""]
    text = "\n".join(parts).rstrip() + "\n"
    text = resolve_figures(pid, text)
    text, cited, f2 = resolve_papers(pid, text)
    fails += f2
    if COMPANIONS in text:
        text = text.replace(COMPANIONS, companion_list(cited))
    elif cited:
        fails.append(f"{pid}: cites companion papers but has no "
                     f"{COMPANIONS} marker")
    stats = {"n_cited": 0, "companions": cited}
    try:
        text, bib, cs = s14_refs.resolve(text)
        stats["n_cited"] = cs["n_cited"]
        if s14_refs.MARKER in text:
            text = text.replace(s14_refs.MARKER, bib)
        else:
            fails.append(f"{pid}: no {{references}} marker")
    except KeyError as exc:
        fails.append(f"{pid}: {exc}")
    for left in sorted(set(re.findall(r"\{(?:fig|paper):[a-z0-9_]+\}",
                                      text))):
        fails.append(f"{pid}: unresolved marker {left}")
    stats["words"] = len(text.split())
    return text, fails, stats


def run(pid: str) -> int:
    text, fails, stats = render(pid)
    (L.paper_dir(pid) / "paper.md").write_text(text, encoding="utf-8")
    for f in fails:
        print(f"  [FAIL] {f}", file=sys.stderr)
    print(f"[s26 stitch {pid}] {stats['words']:,} words, "
          f"{stats['n_cited']} references, "
          f"{len(stats['companions'])} companion paper(s) cited -> "
          f"papers/{pid}/paper.md: {len(fails)} failure(s)")
    return 1 if fails else 0


if __name__ == "__main__":
    sys.exit(run(sys.argv[1]))
