"""s5_report.py — render results/genome_ledger/report.md from committed tables.

D13: nothing in the report is hand-written. Every number is read back out of
the tables the pilot wrote, so the prose and the data cannot drift.

Usage:
  python scripts/s5_report.py
"""

from __future__ import annotations

import json
import statistics
import sys
from collections import Counter
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
for p in (PROJECT_ROOT, PROJECT_ROOT / "scripts"):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))

import s5_sweep_lib as lib                                  # noqa: E402
import s5_report_results as results_sections                # noqa: E402
from s5_rescue import ATTRIBUTION_REL_MARGIN                # noqa: E402
from s5_ledger import STATUS_ORDER                          # noqa: E402

LEDGER = PROJECT_ROOT / "results" / "genome_ledger"
BAITS = PROJECT_ROOT / "results" / "s5_baits"
ALL_CELLS = (*lib.CLASSES, lib.CONTROL_CLASS)


def read_tsv(path: Path) -> list[dict]:
    with path.open() as fh:
        header = fh.readline().rstrip("\n").split("\t")
        return [dict(zip(header, line.rstrip("\n").split("\t")))
                for line in fh if line.strip()]


def load_json(path: Path) -> dict:
    return json.loads(path.read_text())


def table(headers: list[str], rows: list[list]) -> str:
    out = ["| " + " | ".join(headers) + " |",
           "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


def main() -> None:
    bait_stats = load_json(BAITS / "bait_build_stats.json")
    intron = load_json(BAITS / "intron_calibration.json")
    ledger_stats = load_json(LEDGER / "ledger_stats.json")
    margin = load_json(LEDGER / "margin_calibration.json")
    budget = load_json(LEDGER / "s5b_budget.json")
    baits = read_tsv(BAITS / "bait_manifest.tsv")
    self_test = read_tsv(BAITS / "screen_self_test.tsv")
    intron_rows = read_tsv(BAITS / "intron_calibration.tsv")
    wide = read_tsv(LEDGER / "genome_ledger_wide.tsv")
    contiguity = read_tsv(LEDGER / "contiguity_bar.tsv")

    L: list[str] = []
    A = L.append

    is_pilot = bool(ledger_stats.get("is_pilot"))
    swept, scope = ledger_stats["genomes_swept"], ledger_stats["genomes_in_manifest"]
    A("# S5 — the genomic sweep: "
      + ("bait panel, calibrated pipeline, pilot\n" if is_pilot
         else f"{swept} genomes of a declared {scope}\n"))
    A(f"*Generated by `scripts/s5_report.py` from the committed tables "
      f"({bait_stats['built_at']}). Nothing here is hand-written (D13).*\n")
    A("S5 is the genomic sweep that finds ITPRs existing only as DNA and "
      "produces the found/lost/gap ledger an absence claim needs. Its scope "
      f"is S4's declared denominator of {scope} genomes, so it was split per "
      "the session protocol: **S5a** built and calibrated the instrument and "
      "piloted it; **S5b** runs the full sweep and produces census v4.\n")
    if is_pilot:
        A("*This edition reports the pilot. Sections 1-2 describe the "
          "instrument and stand; the results are six genomes.*\n")
    else:
        A(f"*This edition reports the full sweep: {swept} of {scope} genomes. "
          "Sections 1-2 describe the instrument; the results sections test "
          "the pilot's findings rather than repeating them, and print the "
          "pilot's number beside each new one.*\n")

    # ---------------------------------------------------------------- 1
    A("\n## 1. The bait panel\n")
    A(f"{bait_stats['n_baits']} baits — {bait_stats['n_itpr']} ITPR plus "
      f"{bait_stats['n_ryr']} RyR as the internal positive control — "
      f"{bait_stats['total_residues']:,} residues; "
      f"{bait_stats['n_s3_seeds']} reused S3 seeds and "
      f"{bait_stats['n_s5_additions']} additions. The panel is **derived from "
      "`census_v3.tsv` by seven stated rules** (`s5_bait_spec.py`), not "
      "hand-listed, in the shape S4 used for its margin species.\n")
    by_band: dict[str, Counter] = {}
    for b in baits:
        by_band.setdefault(b["band"], Counter())[b["clade"]] += 1
    rows = []
    for band in [b for b in __import__("s5_bait_spec").BANDS if b in by_band]:
        c = by_band[band]
        rows.append([band] + [c.get(k, 0) for k in
                              (*lib.CLASSES, "vertebrate_basal",
                               lib.CONTROL_CLASS)])
    A(table(["clade band", *lib.CLASSES, "unlabelled", "RYR (control)"], rows))
    A("")
    if bait_stats["unfilled_slots"]:
        A(f"**{len(bait_stats['unfilled_slots'])} slots stay empty**: "
          f"{', '.join(bait_stats['unfilled_slots'])}. Not an oversight — the "
          "census holds no labelled, full-length, complete-architecture record "
          "for those paralog x band combinations at all. The paralog labels "
          "run out below the well-annotated clades, and rather than promote an "
          "unlabelled record into a labelled slot (which D5 says does real "
          "damage) the `vertebrate_basal` baits cover those genomes without a "
          "paralog claim and S7 settles the assignment.\n")

    A("### The chimera screen, and its own negative control\n")
    A("D5 asks for a chimera screen. Here that is this project's own "
      "instrument: every candidate **and every incumbent S3 seed** is scored "
      "against `itpr.hmm` and `ryr.hmm` under S3's relative margin (family, "
      "positively — D14) and must show a profile envelope covering the bait "
      "without a large unaligned interior (shape).\n")
    A(f"Across the panel the screen rejected "
      f"{bait_stats['screen_failures']}/{bait_stats['screened']} candidates — "
      "which on its own is not evidence, because a screen that cannot fire "
      "and a shortlist that is clean look identical from outside. So every "
      "build now puts the rules through synthetic failures built from real "
      "panel baits, each aimed at the rule responsible:\n")
    A(table(["synthetic failure", "caught by", "rejected", "reason"],
            [[r["description"].split(" — ")[0], f"`{r['rejected_by']}`",
              "yes" if r["rejected"] == "1" else "**NO**",
              r["reason"]] for r in self_test]))
    A("\nThe test earned its place on first run by failing: it originally "
      "asked the *envelope* to reject a truncation, which it cannot and "
      "should not — a protein truncated to 40 % of its length aligns 100 % of "
      "*itself* to the profile in one clean segment. Truncation is the length "
      "band's job (R2, and S2 found seven real records of exactly that "
      "shape); the envelope's job is fusion.\n")

    # ---------------------------------------------------------------- 2
    A("\n## 2. Calibrating miniprot's `-G`, which is a threshold on the call\n")
    A("miniprot's max-intron default is 200 kb. It is not a performance knob: "
      "a gene whose largest intron exceeds it is **split**, and a split ITPR "
      "reads out of this ledger as `fragment`. S0 measured the *spans* "
      "(human ITPR2 498 kb) but a span over 57 exons is not an intron, so the "
      "question was measured directly across an 11-species Ensembl panel.\n")
    itpr_s, ryr_s = intron["itpr"], intron["ryr"]
    A(table(["family", "genes", "median max intron", "widest", "over 200 kb"],
            [["ITPR", itpr_s["n"], f"{itpr_s['median_max_intron']:,} bp",
              f"{itpr_s['widest_bp']:,} bp ({itpr_s['widest']})",
              f"**{itpr_s['n_over_200kb']}/{itpr_s['n']}**"],
             ["RYR (control)", ryr_s["n"],
              f"{ryr_s['median_max_intron']:,} bp",
              f"{ryr_s['widest_bp']:,} bp ({ryr_s['widest']})",
              f"{ryr_s['n_over_200kb']}/{ryr_s['n']}"]]))
    A(f"\n**No ITPR gene in the panel has an intron over the default** — the "
      f"widest is {itpr_s['widest_bp']:,} bp — while the RyR control exceeds "
      f"it twice. So the default is adequate for the deliverable and marginal "
      "for the control, which is the opposite of what the span figures "
      "suggested.\n")
    rule = intron["max_intron_rule"]
    A(f"The rule the sweep uses: `min({rule['cap_bp']:,}, "
      f"max({rule['floor_bp']:,}, {rule['scale_bp']:,} x genome_bp / "
      f"{rule['anchor_genome_bp']:,}))` — the widest intron measured, doubled, "
      "scaled from the genome it was measured in, floored at miniprot's own "
      "default and capped for tractability. Deliberately **not** the "
      "intron-per-Gbp ratio: that statistic is largest in the *smallest* "
      "genomes measured, and extrapolating it linearly asks for a 7.4 Mbp `-G` "
      "on the lungfish, which is an artefact of a small denominator rather "
      "than a measurement.\n")
    capped = budget["flags"]["giants_needing_chunked_miniprot"]
    if budget["flags"]["genomes_with_capped_max_intron"]:
        A(f"The cap binds on "
          f"{budget['flags']['genomes_with_capped_max_intron']} manifest "
          "genome(s); the ledger flags them, because a `fragment` there could "
          "be a real intron the sweep declined to span.\n")

    # ---------------------------------------------------------------- 3
    A("\n## 3. The pilot\n")
    A(f"{ledger_stats['genomes_swept']} genomes chosen to span the "
      f"classification space, {ledger_stats['loci_recorded']} loci recorded, "
      f"{ledger_stats['control_failures']} RyR control failures.\n")
    A(table(["genome", "class", "N50", *lib.CLASSES, "RYR (control)",
             "spans a gene?"],
            [[f"*{w['organism']}*", w["vclass"], f"{int(w['contig_n50']):,}",
              *[f"{w[c]}" + (f" x{w[c + '_n']}" if int(w[c + "_n"]) > 1 else "")
                for c in lib.CLASSES],
              f"{w['RYR']} x{w['RYR_n']}",
              "yes" if w["contig_spans_gene"] == "1" else "**no**"]
             for w in sorted(wide, key=lambda w: -int(w["contig_n50"] or 0))]))
    A("")
    counts = ledger_stats["status_counts"]
    A("Per cell, over the pilot: "
      + "; ".join(
          f"**{c}** "
          + ", ".join(f"{st} {counts[k]}" for k, st in
                      sorted(((f"{c}:{s}", s) for s in STATUS_ORDER
                              if f"{c}:{s}" in counts),
                             key=lambda kv: STATUS_ORDER.index(kv[1])))
          for c in ALL_CELLS) + ".\n")
    A("No cell in the pilot is `absent`, and that is the correct outcome "
      "rather than a weak one: three of the six assemblies cannot carry an "
      "ITPR gene on a single contig, so their empty cells are evidence about "
      "the assembly and not about the animal.\n")

    A("### What the RyR control bought\n")
    A("The brief asks for one RyR bait per genome as an internal positive "
      "control. It paid immediately. In *Todus mexicanus* — the bird whose "
      "reference proteome carried **no ITPR record at all**, which is why S4 "
      "put it in the margin set — the control found a single RyR locus where "
      "a bird should have three, and that one unannotated. In *Leucopsar "
      "rothschildi* every cell including the control came back "
      "`assembly_gap`. In both, the control says the same thing: what is "
      "missing is contiguity, not genes.\n")

    # ---------------------------------------------------------------- 4
    A("\n## 4. Two constants that did not survive contact with the data\n")
    A("### The unlabelled baits were competing as a fourth paralog\n")
    A("Rescue attribution ranked every bait clade against every other, "
      "`vertebrate_basal` included. Those are the gar, chimaera and lamprey "
      "seeds — unlabelled *ITPR* baits, evidence that a region is an ITPR "
      "rather than a rival hypothesis about which ITPR. Ranking them as a "
      "competitor collapsed real margins: in *Todus* an ITPR1 trace scoring "
      "916.1 against ITPR2's 700.6 — a 0.235 margin — was reported at 0.027, "
      "because `vertebrate_basal` sat between them at 891.6. Every ITPR1 and "
      "ITPR2 trace in that genome was deflated the same way, and three cells "
      "moved from `tblastn_trace_ambiguous` to `tblastn_trace` once the "
      "ranking was restricted to the canonical paralogs.\n")
    A("### The inherited attribution margin is too strict for this family\n")
    A(f"`ATTRIBUTION_REL_MARGIN` arrived as the PIEZO port's 1.5x bit-score "
      f"ratio restated ({margin['inherited_threshold']}), from a family whose "
      "paralogs are 40-50 % identical where these are 61-68 % (S1). Measured "
      "against loci whose paralog identity the assembly's own annotation "
      "establishes and whose call is correct:\n")
    g = margin["groups"]["annotation_agrees_contested"]
    A(table(["contested loci of known identity", "min", "median", "max",
             "below the inherited threshold"],
            [[g["n"], g["min"], g["median"], g["max"],
              f"**{margin['n_contested_below_inherited']}/"
              f"{margin['n_contested']}**"]]))
    A(f"\nA complete locus is an **upper bound** on a rescue fragment, so a "
      "threshold complete evidence fails cannot be met by a fragment: under "
      "the inherited value every rescue trace would be reported ambiguous and "
      f"no absence claim could ever be attributed. The threshold is now "
      f"{ATTRIBUTION_REL_MARGIN} — the highest that rejects none of those "
      "correct calls. Its limitation is stated rather than hidden: it is "
      "derived from complete loci and applied to fragments, so it is a "
      "ceiling on the right answer, not the right answer. S5b re-calibrates "
      "it on rescue regions of known identity, and every region carries its "
      "own margin so a re-cut needs no re-run.\n")
    fam = margin["groups"]["family_margin_all"]
    A(f"**D14, meanwhile, was never in doubt at genome scale.** At all "
      f"{fam['n']} loci only one family's baits aligned at all — the ITPR and "
      "RyR panels never contested a locus. That is a sharper separation than "
      "the protein level gave: S1 measured all six RyR decoys promoted at 45 "
      "before the sister test existed. Spliced alignment against a labelled "
      "panel separates the two families before any margin has to be applied.\n")

    # ---------------------------------------------------------------- 5
    A("\n## 5. D4's contiguity bar, and what it does to the margin set\n")
    A(f"D4 requires a contiguity floor before any absence claim; S19 "
      "calibrates that floor. Pending it, the weaker statement that can be "
      "made now without inventing a number: an assembly whose contig N50 is "
      "below the **median measured ITPR genomic span** "
      f"({budget['flags']['contiguity_bar_bp']:,} bp, from this project's own "
      "`intron_calibration.tsv`) cannot carry the gene on one contig, so a "
      "`fragment` / `assembly_gap` / empty cell there says nothing about "
      "presence.\n")
    A(table(["group", "below the bar", "of", "%"],
            [[c["name"], c["below"], c["total"], f"{float(c['pct']):.0f} %"]
             for c in contiguity if c["below"] != "0"]))
    A(f"\n**{budget['flags']['genomes_below_contiguity_bar']} of "
      f"{sum(int(c['total']) for c in contiguity if c['group'] == 'total')} "
      "manifest genomes fail it, and they are not a random 39 %.** Two thirds "
      "of the birds fail, against 11 % of the ray-finned fish; 68 % of the "
      "margin species fail against 12 % of the order representatives. The "
      "margin set was chosen for what its *proteomes* lack — S4's "
      "`missing_paralog`, `fragment_only`, `zero_hit_proteome` rules — and it "
      "turns out to be very largely the same set of genomes whose assemblies "
      "cannot hold the gene. The two signals are confounded, and S15 cannot "
      "read a bird absence as loss until they are separated.\n")

    A("### The paralog that survives fragmentation is the short one\n")
    spans: dict[str, list[int]] = {}
    for r in intron_rows:
        if r["family"] == "ITPR" and r["span_bp"]:
            spans.setdefault(r["symbol"], []).append(int(r["span_bp"]))
    ledger = read_tsv(LEDGER / "genome_ledger.tsv")
    rows = []
    for p in lib.CLASSES:
        med = int(statistics.median(spans.get(p, [0])))
        cells = {bar: [r for r in ledger if r["class"] == p
                       and r["contig_spans_gene"] == bar] for bar in ("1", "0")}
        found = {bar: sum(1 for r in rs if r["status"].startswith("found"))
                 for bar, rs in cells.items()}
        rows.append([p, f"{med:,} bp",
                     f"{found['1']}/{len(cells['1'])}",
                     f"{found['0']}/{len(cells['0'])}"])
    A(table(["paralog", "median measured span", "found above the bar",
             "found below the bar"], rows))
    A("\nAbove the bar every paralog is found in every genome. Below it, the "
      "one that keeps being recovered is **ITPR3 — the short gene**. S0 found "
      "the 6.5x span asymmetry between paralogs of near-identical protein "
      "length and filed it as a curiosity; here it becomes a detection bias, "
      "because a 231 kb ITPR2 needs a contig a 82 kb ITPR3 does not. So a "
      "fragmented assembly does not lose paralogs at random — it loses the "
      "long ones first, and *that is the same direction as the pattern S4's "
      "margin rules picked these genomes out for*.\n")
    A("Six genomes is a pilot, not a result: this is a mechanism and a "
      "direction, and S5b tests it at 309. But it is the specific confounder "
      "S15 has to defeat before any bird `missing_paralog` is read as loss, "
      "and it predicts which way the error runs.\n")

    # ---------------------------------------------------------------- 6
    A("\n## 6. The budget S5b inherits\n")
    A("Rates measured on clean recomputes, because a cached `miniprot.gff` "
      "makes a rerun look free and that is how a meaningless budget gets "
      f"written: miniprot at **{budget['rates']['miniprot_s_per_gbp']:.0f} "
      "s/Gbp** with 8 threads over the "
      f"{bait_stats['total_residues']:,}-residue panel, identical on a 0.85 "
      "Gbp bird and a 1.86 Gbp mammal; rescue at "
      f"{budget['rates']['rescue_s_per_genome']:.0f} s per genome that needs "
      "it.\n")
    A(table(["group", "genomes", "Gbp", "download GB", "compute h"],
            [[r["group"], r["genomes"], r["gbp"], r["download_gb"],
              r["compute_h"]] for r in budget["groups"]]))
    st = budget["storage"]
    A(f"\n**{budget['remaining_totals']['genomes']} genomes remain: "
      f"{budget['remaining_totals']['compute_h']} h of compute, "
      f"{budget['wall_h_remaining']} h wall at "
      f"{budget['workers_assumed']} shards, "
      f"{budget['remaining_totals']['download_gb']:.0f} GB to download.** "
      f"Keeping every FASTA costs {st['fasta_gb_if_kept']:.0f} GB against "
      f"{st['free_gb_now']:.0f} GB free — it "
      f"{'fits, and saves re-downloading for S8 synteny and S10 validation'
         if st['fits_without_delete_after'] else
         'does not fit; use --delete-after'}.\n")
    if capped:
        A("Two assemblies need the chunked miniprot path and are excluded by "
          "the driver's default 12 GB cut, so S5b runs them separately: "
          + ", ".join(f"*{c['organism']}* ({c['fasta_gb']} GB)"
                      for c in capped) + ".\n")

    if not is_pilot:
        models = (read_tsv(PROJECT_ROOT / "results" / "census_v4"
                           / "genome_models.tsv")
                  if (PROJECT_ROOT / "results" / "census_v4"
                      / "genome_models.tsv").exists() else [])
        v4stats = (load_json(PROJECT_ROOT / "results" / "census_v4"
                             / "census_v4_stats.json")
                   if (PROJECT_ROOT / "results" / "census_v4"
                       / "census_v4_stats.json").exists() else {})
        ledger_rows = read_tsv(LEDGER / "genome_ledger.tsv")
        R = results_sections
        R.section_control(A, table, ledger_rows, wide, ledger_stats)
        R.section_ledger(A, table, ledger_rows, ledger_stats, STATUS_ORDER,
                         list(lib.CLASSES))
        R.section_contiguity(A, table, ledger_rows, contiguity,
                             budget["flags"]["contiguity_bar_bp"],
                             list(lib.CLASSES))
        R.section_d14(A, table, margin, R.PILOT["total_loci"])
        R.section_margin(A, table, margin, ATTRIBUTION_REL_MARGIN)
        R.section_census(A, table, v4stats, models)
        R.section_discrepancies(A, table, models)

    A("\n## Outputs\n")
    A("- `results/s5_baits/` — the panel, its per-candidate screen, the "
      "screen's own negative controls, and the intron calibration\n"
      "- `results/genome_ledger/` — the pilot ledger (long and wide), status "
      "counts, per-locus margins, the margin calibration, the contiguity "
      "table and the S5b budget\n"
      f"- `{ledger_stats['genomes_swept']}` per-genome evidence directories "
      "under the data root (`genome_sweep/<acc>/`), each with its raw "
      "miniprot GFF, rescue output and `summary.json`\n")

    out = LEDGER / "report.md"
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out} ({len(L)} blocks)")


if __name__ == "__main__":
    main()
