"""S6 — renders `results/msa_v2/report.md` purely from the committed tables.

D13: nothing in that report is hand-written. Scope and instrument live here,
results in `s6_report_results.py` (the `s3_report.py` / `s3_report_d10.py`
split, so both halves stay under 500 lines and cannot read the tables
differently — the results half takes this module's loader and formatter).

Run:  /opt/anaconda3/envs/piezo1/bin/python scripts/s6_report.py
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import s6_rep_spec as spec                                   # noqa: E402
from s6_lib import MSA_DIR, read_tsv                         # noqa: E402


def load(name: str) -> list[dict]:
    p = MSA_DIR / name
    return read_tsv(p) if p.exists() else []


def load_json(name: str) -> dict:
    p = MSA_DIR / name
    return json.loads(p.read_text()) if p.exists() else {}


def num(v, nd=0) -> str:
    try:
        f = float(v)
    except (TypeError, ValueError):
        return str(v)
    return f"{f:,.{nd}f}"


def table(header: list[str], rows: list[list]) -> list[str]:
    out = ["| " + " | ".join(header) + " |",
           "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return out + [""]


# ------------------------------------------------------------------ scope

def section_scope(reps: list[dict], sel: dict) -> list[str]:
    by_rule = Counter(r["rule"].split("+")[0] for r in reps)
    by_group = Counter(r["group"] for r in reps)
    rule_text = {
        "R1": "the vertebrate paralog grid — clade band x ITPR1/2/3, two "
              "records in the three bands that dominate the vertebrate "
              "census, human forced in",
        "R2": "the teleost 3R co-orthologs — `itprXa`/`itprXb` pairs, the "
              "family's only other documented duplication",
        "R3": "the deep vertebrate grade, entered **unlabelled** — "
              "cyclostomes, chondrichthyans, the coelacanth grade",
        "R4": "non-vertebrate metazoa, one per phylum and more in the four "
              "phyla that dominate that part of the census",
        "R5": "non-metazoan eukaryotes, per group and phylum, gated on "
              "S20's per-record plant/fungal verdict",
        "R6": "the copy-number expansions — S23 measured 0-18 copies "
              "outside the vertebrates, so the expanded genomes get more "
              "than one tip",
        "R7": "the novel gene models no database annotates (`genome_only`)",
        "R8": "the ryanodine-receptor outgroup, which roots the tree",
    }
    L = ["# S6 — the representative alignment (`msa_v2`)", "",
         f"*Generated by `scripts/s6_report.py` from the committed tables in "
         f"`results/msa_v2/`. {len(reps)} representatives selected from "
         f"{num(sel.get('census_rows', 0))} census v6 records.*", "",
         "The publication-quality alignment every downstream result stands "
         "on: S7's tree and AU test, S9's codon alignment, S11's constraint "
         "mapping, S17's conservation. What it has to get right is not the "
         "aligner — it is **which sequences are in it**, because a "
         "representative set is a sampling decision the tree inherits as a "
         "topology.", "",
         "## 1. The representative set", "",
         "Chosen by the eight coded rules in `scripts/s6_rep_spec.py` (D8: "
         "per clade *and* per kingdom, explicit rules, never longest-per-"
         "species). Every chosen row carries the rule, the cell it filled, "
         "the runner-up it beat and which component of the quality key "
         "separated them — see `representatives.tsv`.", ""]
    L += table(["rule", "what it selects", "n"],
               [[r, rule_text.get(r, ""), by_rule[r]]
                for r in sorted(by_rule)])
    L += ["Composition by group:", ""]
    L += table(["group", "n", "median length (aa)"],
               [[g, by_group[g],
                 num(sorted(int(r["length"]) for r in reps
                            if r["group"] == g)[by_group[g] // 2])]
                for g in spec.GROUP_ORDER if by_group[g]])
    L += [f"Total {num(sel.get('total_residues', 0))} residues; longest "
          f"{num(sel.get('longest', 0))} aa (a ryanodine receptor — the "
          f"outgroup is ~5,000 aa against the family's ~2,700, which is why "
          f"the alignment is mostly gap).", ""]
    return L


def section_rules_evidence(reps: list[dict], sel: dict) -> list[str]:
    dec = Counter(r["decided_by"] for r in reps)
    L = ["### 1.1 What actually decided each pick", "",
         "The quality key is lexicographic, not a weighted sum, so the audit "
         "can name the component that chose the winner. Identity appears "
         "nowhere in it: S23 (**D29**) retired identity as a call gate for "
         "this family outside the vertebrates after finding it separates "
         "neither confirmed from contradicted loci (Youden J 0.70/0.71), and "
         "a selection rule stated in a statistic that does not separate the "
         "populations is not a rule.", ""]
    L += table(["decided by", "n"],
               [[k, v] for k, v in sorted(dec.items(), key=lambda kv: -kv[1])])
    tgt = sel.get("length_targets", {})
    L += ["The length-fit component scores a record against **its own "
          "group's median**, measured from the census's complete-"
          "architecture non-fragment ITPR records rather than typed:", ""]
    L += table(["group", "median length (aa)"],
               [[k, num(v)] for k, v in sorted(tgt.items())
                if k != "__default__"])
    return L


def section_unfilled(reps: list[dict]) -> list[str]:
    un = load("unfilled_slots.tsv")
    sel = load_json("selection_stats.json")
    L = ["### 1.2 The slots the census could not fill", ""]
    if not un:
        L += ["Every slot filled.", ""]
    else:
        L += [f"{len(un)} slots stayed empty, and each names the stage that "
              f"lost it rather than blaming the census in general:", ""]
        L += table(["rule", "cell", "wanted", "filled", "pool", "why"],
                   [[u["rule"], f"`{u['cell']}`", u["wanted"], u["filled"],
                     u["pool"], u["why"]] for u in un])
        ctx = sel.get("unfilled_context", {})
        if ctx:
            L += ["Each of those cells against what the census actually "
                  "holds in that clade band, because three statements have "
                  "to be told apart: no record at all, no record carrying "
                  "an annotation label, and no record whose label is a "
                  "paralog *assignment* rather than a bait attribution. "
                  "Only the last two are results.", ""]
            L += table(["cell", "ITPR records", "distinct loci",
                        "with any label", "with a *usable* label",
                        "labels present"],
                       [[f"`{c}`", d["itpr_records_in_band"],
                         d["loci_in_band"], d["with_any_label"],
                         d["with_a_usable_label"],
                         ", ".join(d["labels_present"]) or "—"]
                        for c, d in sorted(ctx.items())])
            cyc = {c: d for c, d in ctx.items() if "cyclostomata" in c}
            if cyc:
                d = next(iter(cyc.values()))
                L += [f"**The cyclostome rows are a result.** That band "
                      f"holds {num(d['itpr_records_in_band'])} ITPR records "
                      f"over {num(d['loci_in_band'])} distinct loci; "
                      f"{num(d['with_any_label'])} carry a paralog label of "
                      f"any kind"
                      + (f" (only {', '.join(d['labels_present'])}, and only "
                         f"from {', '.join(d['label_sources'])})"
                         if d["labels_present"] else "")
                      + f", and {num(d['with_a_usable_label'])} carry one "
                        f"this task will use. The sea lamprey and the "
                        f"hagfishes each carry **three** ITPR loci, and the "
                        f"sweep's ITPR1 bait wins every one of them — a "
                        f"constant attribution, which is no information "
                        f"about which locus is which. R3 therefore takes "
                        f"the complete copy set of two cyclostome species "
                        f"unlabelled, which is the honest input to S7: "
                        f"whether those three are 1:1 orthologs of "
                        f"ITPR1/2/3 or a lineage-specific expansion is the "
                        f"2R question, and a set carrying one lamprey tip "
                        f"could not answer it.", ""]
    short = sel.get("short_exceptions", [])
    if short:
        L += [f"{len(short)} representatives entered under the "
              f"architecture-exception floor (below the family's "
              f"{spec.ITPR_MIN_AA:,} aa band but at or above "
              f"{spec.SHORT_EXCEPTION_MIN_AA:,} aa), because their clade's "
              f"only records are short and a clade with no tip cannot carry "
              f"the range claim S20/S23 made about it:", ""]
        L += ["- `" + s + "`" for s in short] + [""]
    return L


# ------------------------------------------------------------- instrument

def section_alignment(stats: dict) -> list[str]:
    m, t = stats.get("mafft", {}), stats.get("trimal", {})
    if not m:
        return ["## 2. The alignment", "", "*Not yet built.*", ""]
    L = ["## 2. The alignment", "",
         f"- Aligner: **MAFFT {m['aligner']}** ({m['version']}) — "
         f"{m['why']}.",
         f"- Command: `{m['command']}`",
         f"- **Single-threaded, by decision (D24).** MAFFT L-INS-i at "
         f"`--thread -1` is not reproducible on this machine: S3 aligned the "
         f"same 22 RyR seeds twice and got 8,510 and 8,468 columns, because "
         f"the iterative refinement stage combines partial results in "
         f"whatever order the threads finish. Everything downstream of this "
         f"file is built from it, so it is pinned to one thread and the "
         f"SHA-256 of input and output are recorded.",
         f"- Runtime: {num(m['runtime_s'] / 60, 1)} min "
         f"({num(m['runtime_s'])} s).",
         f"- Result: **{num(m['columns'])} columns**, {m['gap_pct']} % gaps, "
         f"{m['n_sequences']} sequences.",
         f"- `sha256(representatives.fasta)` = `{m['sha256_in'][:16]}…`; "
         f"`sha256(aln.fasta)` = `{m['sha256_out'][:16]}…`.", "",
         "The alignment is checked for raggedness before anything reads it. "
         "S1 established that a silent MAFFT failure does not error — it "
         "degrades to a star alignment with no other symptom — so unequal "
         "row lengths are a hard failure here rather than a warning.", ""]
    if t:
        L += ["## 3. Trimming", "",
              f"- {t['version']}",
              f"- Command: `{t['command']}` ({num(t['runtime_s'], 1)} s)",
              f"- **{num(t['columns_kept'])} of {num(t['columns_in'])} "
              f"columns kept ({t['pct_kept']} %)**, {t['gap_pct']} % gaps "
              f"after trimming.", "",
              f"`-automated1` is trimAl's own heuristic for a "
              f"phylogeny-bound alignment; the choice is recorded rather "
              f"than tuned, because a trimming threshold picked by looking "
              f"at the resulting tree is a threshold fitted to the answer.",
              ""]
    return L


def main() -> int:
    reps = load("representatives.tsv")
    if not reps:
        raise SystemExit("run scripts/s6_select_reps.py first")
    sel = load_json("selection_stats.json")
    stats = load_json("align_stats.json")
    L = section_scope(reps, sel)
    L += section_rules_evidence(reps, sel)
    L += section_unfilled(reps)
    L += section_alignment(stats)
    import s6_report_results as res
    L += res.render(load=load, load_json=load_json, table=table, num=num,
                    reps=reps, stats=stats)
    (MSA_DIR / "report.md").write_text("\n".join(L) + "\n")
    write_stats_md(reps, sel, stats)
    print(f"wrote {MSA_DIR / 'report.md'} ({len(L)} lines) and stats.md")
    return 0


def write_stats_md(reps: list[dict], sel: dict, stats: dict) -> None:
    """The brief's named artefact: length, %gaps, columns kept, in one page.

    `report.md` is the D13-rendered document and carries the reasoning;
    this is the digest the S6 brief asks for by name, rendered from the same
    `align_stats.json` so the two cannot disagree.
    """
    m, t = stats.get("mafft", {}), stats.get("trimal", {})
    cov = load("coverage.tsv")
    L = ["# S6 — `msa_v2` alignment statistics", "",
         "*Generated by `scripts/s6_report.py` from `align_stats.json` and "
         "`coverage.tsv`. The reasoning is in `report.md`; this is the "
         "digest.*", ""]
    rows = [["representatives", num(len(reps))],
            ["total residues", num(sel.get("total_residues", 0))],
            ["longest sequence (aa)", num(sel.get("longest", 0))]]
    if m:
        rows += [["aligner", f"MAFFT {m['aligner']} ({m['version']})"],
                 ["threads", f"{m['threads']} (D24)"],
                 ["MAFFT runtime", f"{num(m['runtime_s'] / 60, 1)} min"],
                 ["alignment length (columns)", num(m["columns"])],
                 ["alignment gaps", f"{m['gap_pct']} %"]]
    if t:
        rows += [["trimAl", t["version"]],
                 ["trimAl mode", "-automated1"],
                 ["columns kept", f"{num(t['columns_kept'])} "
                                  f"({t['pct_kept']} %)"],
                 ["trimmed gaps", f"{t['gap_pct']} %"]]
    if cov:
        v = sorted(float(r["coverage"]) for r in cov)
        rows += [["median tip coverage of trimmed MSA", f"{v[len(v) // 2]:.2f}"],
                 ["tips under 0.5 coverage",
                  f"{sum(1 for x in v if x < 0.5)} of {len(v)}"]]
    L += table(["quantity", "value"], rows)
    (MSA_DIR / "stats.md").write_text("\n".join(L) + "\n")


if __name__ == "__main__":
    raise SystemExit(main())
