"""S7 — renders `results/phylogeny/report.md` purely from the committed
tables (D13).

Scope and instrument live here; the results live in
`s7_report_results.py` (the `s3_report.py` / `s3_report_d10.py` split, so
both halves stay under 500 lines and take this module's loader and
formatter and so cannot read the tables differently).

The report titles itself from the tree it is rendering — model, tip count
and support scheme — for the same reason `s5_report.py` does: a pilot and
a full run must not be able to wear each other's heading.

Run:  python3 scripts/s7_report.py
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from s6_lib import read_tsv                                   # noqa: E402
from s7_lib import MSA_DIR, PHYLO_DIR                         # noqa: E402


def load(name: str) -> list[dict]:
    p = PHYLO_DIR / name
    return read_tsv(p) if p.exists() else []


def load_json(name: str) -> dict:
    p = PHYLO_DIR / name
    return json.loads(p.read_text()) if p.exists() else {}


def num(v, nd=0) -> str:
    try:
        f = float(v)
    except (TypeError, ValueError):
        return str(v)
    return f"{f:,.{nd}f}"


def table(header: list[str], rows: list[list]) -> list[str]:
    out = ["| " + " | ".join(header) + " |",
           "|" + "|".join("---" for _ in header) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return out + [""]


# ------------------------------------------------------------------ scope

def section_scope(reps: list[dict], stats: dict) -> list[str]:
    iq = stats.get("iqtree", {})
    n = iq.get("n_sequences", len(reps))
    cols = iq.get("columns", "")
    by_group = Counter(r["group"] for r in reps)
    ing = sum(v for g, v in by_group.items() if g != "RYR")
    L = [f"# S7 — the ML phylogeny of the ITPR family "
         f"({n} tips, {num(cols)} columns)", "",
         "*Generated by `scripts/s7_report.py` from the committed tables in "
         "`results/phylogeny/`. Nothing here is hand-written (D13): every "
         "number is read from a file this task wrote, and the verdicts are "
         "computed by comparing those numbers against the priors the "
         "earlier tasks recorded.*", "",
         "## 1. What is in the tree", "",
         f"S6's trimmed alignment, unchanged: **{n} sequences × "
         f"{num(cols)} columns**, of which "
         f"{num(load_json_msa('align_stats.json').get('sites', {}).get('parsimony_informative', ''))} "
         "are parsimony-informative. The ingroup is "
         f"**{ing}** ITPR records spanning vertebrates, invertebrates, "
         "protists, plants and fungi; the outgroup is "
         f"**{by_group.get('RYR', 0)}** ryanodine receptors, the sister "
         "family that carries every ITPR-diagnostic Pfam domain (D14) and "
         "is therefore the only outgroup this family has that is close "
         "enough to align and distant enough to root.", ""]
    rows = [[g, by_group[g]] for g in
            ["ITPR1", "ITPR2", "ITPR3", "vertebrate_basal", "invert_metazoa",
             "protist", "plant", "fungi", "RYR"] if by_group.get(g)]
    L += table(["group (census label)", "tips"], rows)
    L += ["The three paralog labels are the census's, not the tree's. "
          "Whether they are clades at all is §4.1; §4.2 is what the task "
          "exists to answer.", ""]
    return L


def load_json_msa(name: str) -> dict:
    p = MSA_DIR / name
    return json.loads(p.read_text()) if p.exists() else {}


# ------------------------------------------------------------- instrument

def section_model(choice: dict) -> list[str]:
    if not choice:
        return []
    probe = choice.get("exhaustive_probe", {})
    a, b = choice.get("stage_a", {}), choice.get("stage_b", {})
    L = ["## 2. The model, and why it was not chosen by `-m MFP`", "",
         "The brief's command is `-m MFP` — ModelFinder's exhaustive scan. "
         "It was started, measured and abandoned, and the measurement is "
         "the reason:", ""]
    rows = [["models scored before the stop",
             f"{probe.get('models_scored', '')} of up to "
             f"{num(probe.get('of_up_to', ''))}"],
            ["wall clock for those",
             f"{num(probe.get('seconds', ''))} s at "
             f"{probe.get('threads', '')} threads"],
            ["projected full scan",
             f"**~{probe.get('projection_hours', '')} h**"]]
    L += table(["measurement", "value"], rows)
    w = probe.get("why_freerate_matters", {})
    if w:
        L += [f"The cost is the free-rate models, and they are not "
              f"optional on this alignment: `LG+R5` beats `LG+I+G4` by "
              f"**{num(w.get('bic_gain'), 1)} BIC units** "
              f"({num(w.get('LG+R5_bic'), 1)} against "
              f"{num(w.get('LG+I+G4_bic'), 1)}), so dropping `+R` to buy "
              "the time back would have returned a measurably worse "
              "model. The scan was replaced by a greedy two-stage "
              "selection, with both stages' tables committed to "
              "`model_selection.tsv`:", ""]
    rows = [["A — matrix",
             f"every matrix, rate fixed at `{a.get('rates_tested', '')}`",
             f"{a.get('models_scored', '')} models over "
             f"{a.get('matrices_scored', '')} matrices",
             f"**{a.get('best_model', '')}**"],
            ["B — rate heterogeneity",
             f"`{choice.get('matrix', '')}` alone, every rate model",
             f"{b.get('models_scored', '')} models",
             f"**{b.get('best_model', '')}**"]]
    L += table(["stage", "scanned", "size", "best by BIC"], rows)
    L += [f"Stage A picked `{choice.get('matrix', '')}` over "
          f"`{a.get('runner_up_matrix', '')}` by "
          f"**{num(a.get('bic_margin'), 1)} BIC units**; stage B then "
          f"bought a further **{num(b.get('bic_gain_over_stage_a'), 1)}** "
          f"by changing only the rate model. The tree is built under "
          f"**`{choice.get('final_model', '')}`**.", "",
          "**What this costs, stated rather than buried.** The matrix that "
          "wins under `+G4` need not be the matrix that would win under "
          "the final rate model. That is the bet a greedy two-stage "
          "selection makes, and the margin it was made on is in the table "
          "above rather than in a sentence — `model_selection.tsv` carries "
          "every model either stage scored, so how close the second-best "
          "matrix came is checkable rather than asserted.", ""]
    return L


def section_search(stats: dict) -> list[str]:
    iq = stats.get("iqtree", {})
    if not iq:
        return []
    L = ["## 3. The search", "",
         "One IQ-TREE run, its command and its inputs' checksums recorded "
         "so a rebuild that drifts is visible in the data (D24, the "
         "discipline S6 applied to MAFFT):", ""]
    rows = [["version", iq.get("version", "")],
            ["command", f"`{iq.get('command', '')}`"],
            ["threads", f"{iq.get('threads', '')} — {iq.get('thread_note', '')}"],
            ["seed", iq.get("seed", "")],
            ["model", f"`{iq.get('model', '')}`"],
            ["log-likelihood", num(iq.get("log_likelihood"), 3)],
            ["branch support",
             f"{num(iq.get('alrt_replicates'))} SH-aLRT + "
             f"{num(iq.get('ufboot_replicates'))} ultrafast bootstrap"],
            ["runtime", f"{num(iq.get('runtime_s', 0) / 60, 1)} min"],
            ["SHA-256 (alignment)", f"`{str(iq.get('sha256_in', ''))[:16]}…`"],
            ["SHA-256 (treefile)",
             f"`{str(iq.get('sha256_treefile', ''))[:16]}…`"]]
    L += table(["", ""], rows)
    L += ["Support is reported as **SH-aLRT / UFBoot** throughout, and a "
          "node counts as well supported only when it clears **both** of "
          "IQ-TREE's own thresholds — SH-aLRT ≥ 80 *and* UFBoot ≥ 95. One "
          "of the two alone is not enough: UFBoot is known to be "
          "optimistic under model violation, which is exactly the "
          "condition a 134-tip alignment spanning four kingdoms is in.", ""]
    return L


def section_rooting(rooting: list[dict]) -> list[str]:
    if not rooting:
        return []
    r = rooting[0]
    mono = r["monophyletic"] == "yes"
    L = ["## 4. Rooting, and the control it doubles as", "",
         f"The tree is rooted on the **ryanodine receptors** "
         f"(n={r['n']}), the outgroup the brief names. That choice is also "
         "a control on the whole alignment: the RyRs are the family this "
         "project has spent every stage separating from the ITPRs by a "
         "positive test (D14), and if they did not come back as a clade "
         "here, the alignment underneath every downstream result would be "
         "the thing to doubt.", ""]
    if mono:
        L += [f"They do. The {r['n']} RyR tips are **monophyletic**, and "
              f"the root is placed on the edge separating them from the "
              f"ITPR ingroup. `{r['rooted_file']}` is what the figure "
              "draws.", ""]
    else:
        L += [f"**They do not.** The largest pure RyR clade holds "
              f"{r['largest_pure_clade']} of {r['n']} tips, so the root is "
              f"placed on that edge and the remaining RyR tips fall inside "
              f"the ingroup. That is a caveat on every rooted statement "
              f"below, and it is recorded in `rooting.tsv` rather than "
              f"smoothed over.", ""]
    return L


def main() -> int:
    reps = read_tsv(MSA_DIR / "representatives.tsv")
    stats = load_json("tree_stats.json")
    choice = load_json("model_choice.json")
    if not stats.get("iqtree"):
        raise SystemExit("run scripts/s7_run.py ml first")
    L = section_scope(reps, stats)
    L += section_model(choice)
    L += section_search(stats)
    L += section_rooting(load("rooting.tsv"))
    import s7_report_results as res
    L += res.render(load=load, load_json=load_json, table=table, num=num,
                    reps=reps, stats=stats)
    out = PHYLO_DIR / "report.md"
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out} ({len(L)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
